import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { DisasterProvider } from '../../../server/plugins/disaster/provider.ts';
import { defaultSettings } from '../../../server/plugins/disaster/catalog.ts';
import { DisasterStore } from '../../../server/plugins/disaster/store.ts';
import { openDatabases } from '../../../server/db/connection.ts';
import { seedProfiles } from '../../../server/core/session.ts';
import { readFileSync } from 'node:fs';
const migration={id:'disaster-001',sql:readFileSync(new URL('../../../server/db/migrations/disaster/001-cache.sql',import.meta.url),'utf8')};
const path='.local/disaster-live-evidence';mkdirSync(path,{recursive:true});
const options={livePath:`${path}/live.sqlite`,demoPath:`${path}/demo.sqlite`,migrations:[migration]};
let dbs=openDatabases(options);
const profile={key:'disaster-evidence',id:'disaster-evidence-person',name:'防災実取得検証'};
seedProfiles(dbs,[profile]);
const context={personId:profile.id,dataMode:'live' as const,requestId:randomUUID(),signal:new AbortController().signal};
const layers=await new DisasterProvider().fetchLayers(defaultSettings,context.signal);
const now=Date.now();
const snapshot={resultId:randomUUID(),dataKind:'live' as const,settings:defaultSettings,installId:'provider-evidence-only',settingsVersion:1,pluginVersion:'1.0.0',fetchedAt:now,expiresAt:now+600000,status:layers.some(l=>l.status!=='available') ? 'partial' as const : 'available' as const,layers,unknowns:['Provider/SQLite evidence only; plugin HTTP integration is separately verified.']};
new DisasterStore(dbs.live,context).save(snapshot,{attemptedAt:now,status:layers.every(l=>l.tiles.length && l.tiles.every(t=>t.status==='available')) ? 'complete' : 'partial',settings:defaultSettings,layers});
dbs.close();
dbs=openDatabases(options);
const restored=new DisasterStore(dbs.live,context).read().result;
assert.deepEqual(restored,snapshot);
assert.equal(new DisasterStore(dbs.demo,{...context,dataMode:'demo'}).read().result,null);
dbs.close();
const evidence={verifiedAt:new Date().toISOString(),context:{personId:profile.id,dataMode:'live'},settings:defaultSettings,sqliteReopenExactMatch:true,demoIsolated:true,
  layers:layers.map(l=>({...l,tiles:l.tiles.map(({imageDataUrl,...t})=>({...t,savedImageBytes:imageDataUrl ? Buffer.from(imageDataUrl.split(',')[1]!,'base64').length : 0}))}))};
writeFileSync(new URL('./live-provider.json',import.meta.url),JSON.stringify(evidence,null,2)+'\n');
console.log(JSON.stringify({sqliteReopenExactMatch:true,layers:layers.map(l=>({id:l.layerId,status:l.status,tiles:l.tiles.length,sourceUpdatedAt:l.sourceUpdatedAt,validAt:l.validAt,errors:l.tiles.filter(t=>t.error).map(t=>t.error)}))}));
assert.ok(layers.every(l=>l.status==='available'),'Every real layer must be available for successful evidence');
