import './transfer.css';

// Layout follows rehearsal src/features/transfer/entry.tsx and styles.css.
export const transferMessages = {
  eyebrow: '体験を持って、次の街へ', title: '別の街で試す', description: '場所が変わっても、大切にしたい順番と理由を残しましょう。',
  saved: '保存したレシピ・後で見る案', source: '1. 元の体験を確かめる', name: 'レシピの名前', original: '元の体験', select: '選択してください', stage: '体験の段階', role: '役割', purpose: '目的', reason: 'その理由', originalPlace: '元の場所', required: '必須条件（読点区切り）', changeable: '変更してよい条件', memory: '移せない記憶', stay: '滞在（分）', previous: '前の段階へ移動', remove: 'この段階を削除', add: '段階を追加', order: '順番が持つ意味', save: 'レシピを保存',
  destination: '2. 次の街と自分の条件', city: '移し替え先', desire: '今回、自分が楽しみたいこと', time: '使える時間（分）', cost: '費用上限（円）', requireOpen: '営業中であることを必須にする', compare: '忠実 / 自分向けを比較', result: '3. 元の意味と変更点を読む', faithful: '元の体験に忠実', personal: '自分向けにアレンジ', nextPlace: '次の街で試す', retained: '維持したこと', changed: '変更したこと', nonTransferable: '移せないこと', unknown: '未確認', adopt: 'この案で行く', defer: '後で', noPlan: '条件を確認して、二つの案を比較します。', processing: '保存・確認しています…',
  draft: '未保存の変更があります', originalUnchanged: '元の記録は書き換えません。', noComparison: '比較できる候補がありません。移し替え先や条件を見直してください。', routeNote: '「この案で行く」で採用した地点の順番を経路へ渡します。訪問と感想は、そのあと本人の記録として残します。', retry: '再試行',
};

/** Form fields; the transfer feature's confirmed API maps these to its recipe and plan DTOs. */
export interface TransferDraftPresentation {
  name: string; sourceRecordId: string; sequenceReason: string;
  roles: { key: string; label: string; purpose: string; reason: string; sourcePlaceName: string; required: string; changeable: string; memory: string; stayMinutes: string }[];
  city: string; desire: string; timeMinutes: string; costYen: string; requireOpen: boolean;
}
export interface TransferPlanPresentation {
  id: string; mode: 'faithful' | 'personal'; label: string; status: string; adoptable: boolean;
  roles: { key: string; originalLabel: string; originalReason: string; placeName: string; retained: string[]; changed: string[]; nonTransferable: string[]; unknown: string[] }[];
  warnings: string[];
}

export function TransferView({ draft, records, plans, selectedId, savedItems, dirty, busy, error, notice, onDraft, onAddRole, onRemoveRole, onMoveRole, onSave, onCompare, onSelect, onAdopt, onDefer, onReopen, onRetry }: {
  draft: TransferDraftPresentation; records: { id: string; label: string }[]; plans: TransferPlanPresentation[]; selectedId: string | null; savedItems: { id: string; label: string }[];
  dirty: boolean; busy: boolean; error: string | null; notice: string | null;
  onDraft: (draft: TransferDraftPresentation) => void; onAddRole: () => void; onRemoveRole: (key: string) => void; onMoveRole: (key: string) => void;
  onSave: () => void; onCompare: () => void; onSelect: (id: string) => void; onAdopt: () => void; onDefer: () => void; onReopen: (id: string) => void; onRetry: () => void;
}) {
  const m = transferMessages;
  const selected = plans.find(plan => plan.id === selectedId);
  const edit = (patch: Partial<TransferDraftPresentation>) => onDraft({ ...draft, ...patch });
  const role = (key: string, patch: Partial<TransferDraftPresentation['roles'][number]>) => edit({ roles: draft.roles.map(item => item.key === key ? { ...item, ...patch } : item) });
  return <section className="transfer-workbench" aria-label={m.title}><header><p>{m.eyebrow}</p><h2>{m.title}</h2><p>{m.description}</p></header>{savedItems.length > 0 && <details><summary>{m.saved}（{savedItems.length}件）</summary><div className="transfer-saved">{savedItems.map(item => <button type="button" key={item.id} onClick={() => onReopen(item.id)} disabled={busy}>{item.label}</button>)}</div></details>}
    <fieldset disabled={busy}><legend>{m.source}</legend><label>{m.name}<input value={draft.name} onChange={e => edit({ name: e.target.value })}/></label><label>{m.original}<select value={draft.sourceRecordId} onChange={e => edit({ sourceRecordId: e.target.value })}><option value="">{m.select}</option>{records.map(record => <option key={record.id} value={record.id}>{record.label}</option>)}</select></label>{draft.roles.map((item, index) => <article key={item.key} className="transfer-role"><h3>{index + 1}. {item.label || m.stage}</h3><div className="transfer-grid"><label>{m.role}<input value={item.label} onChange={e => role(item.key, { label: e.target.value })}/></label><label>{m.purpose}<input value={item.purpose} onChange={e => role(item.key, { purpose: e.target.value })}/></label></div><label>{m.reason}<textarea value={item.reason} onChange={e => role(item.key, { reason: e.target.value })}/></label>{item.sourcePlaceName && <p>{m.originalPlace}: {item.sourcePlaceName}</p>}<div className="transfer-grid"><label>{m.required}<input value={item.required} onChange={e => role(item.key, { required: e.target.value })}/></label><label>{m.changeable}<input value={item.changeable} onChange={e => role(item.key, { changeable: e.target.value })}/></label></div><label>{m.memory}<textarea value={item.memory} onChange={e => role(item.key, { memory: e.target.value })}/></label><div className="transfer-grid"><label>{m.stay}<input type="number" min="0" value={item.stayMinutes} onChange={e => role(item.key, { stayMinutes: e.target.value })}/></label><button type="button" disabled={index === 0} onClick={() => onMoveRole(item.key)}>{m.previous}</button></div><button type="button" disabled={draft.roles.length === 1} onClick={() => onRemoveRole(item.key)}>{m.remove}</button></article>)}<button type="button" onClick={onAddRole}>{m.add}</button><label>{m.order}<textarea value={draft.sequenceReason} onChange={e => edit({ sequenceReason: e.target.value })}/></label><button type="button" onClick={onSave} disabled={!draft.name.trim()}>{m.save}</button>{dirty && <p className="transfer-note">{m.draft}</p>}<p className="transfer-note">{m.originalUnchanged}</p></fieldset>
    <fieldset disabled={busy}><legend>{m.destination}</legend><label>{m.city}<input value={draft.city} onChange={e => edit({ city: e.target.value })}/></label><label>{m.desire}<input value={draft.desire} onChange={e => edit({ desire: e.target.value })}/></label><div className="transfer-grid"><label>{m.time}<input type="number" min="1" value={draft.timeMinutes} onChange={e => edit({ timeMinutes: e.target.value })}/></label><label>{m.cost}<input type="number" min="0" value={draft.costYen} onChange={e => edit({ costYen: e.target.value })}/></label></div><label className="transfer-choice"><input type="checkbox" checked={draft.requireOpen} onChange={e => edit({ requireOpen: e.target.checked })}/>{m.requireOpen}</label><div className="transfer-actions"><button type="button" className="transfer-primary" disabled={!draft.city.trim() || !draft.sourceRecordId} onClick={onCompare}>{m.compare}</button></div></fieldset>
    {error && <div role="alert" className="transfer-error"><p>{error}</p><button type="button" onClick={onRetry}>{m.retry}</button></div>}{notice && <p className="transfer-note" role="status">{notice}</p>}{busy && <p role="status">{m.processing}</p>}
    {plans.length > 0 && <section aria-label={m.result}><h3>{m.result}</h3><div className="transfer-actions">{plans.map(plan => <button type="button" key={plan.id} aria-pressed={plan.id === selectedId} onClick={() => onSelect(plan.id)}>{plan.mode === 'faithful' ? m.faithful : m.personal}</button>)}</div>{selected && <><p>{selected.label} · {selected.status}</p>{selected.roles.map(item => <article className="transfer-comparison" key={item.key}><div><small>{m.original}</small><h4>{item.originalLabel}</h4><p>{item.originalReason}</p></div><div><small>{m.nextPlace}</small><h4>{item.placeName}</h4>{(['retained','changed','nonTransferable','unknown'] as const).map(key => <div key={key}><strong>{m[key]}</strong><ul>{item[key].map((text, index) => <li key={index}>{text}</li>)}</ul></div>)}</div></article>)}{selected.warnings.map((warning, index) => <p className="transfer-error" key={index}>{warning}</p>)}<div className="transfer-actions"><button type="button" className="transfer-primary" disabled={busy || dirty || !selected.adoptable} onClick={onAdopt}>{m.adopt}</button><button type="button" disabled={busy || dirty} onClick={onDefer}>{m.defer}</button></div><p className="transfer-note">{m.routeNote}</p></>}</section>}
  </section>;
}
