// Explicit display fixture. Not imported by the product's screen registry.
import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CheckinView,SuggestionsView,SuggestionDetailView,FeatureHeader} from '../../../src/features/suggestions/views';
import {SuggestionIcon as Icon} from '../../../src/features/suggestions/icons';
import type {CandidateView,CheckinForm,Notice} from '../../../src/features/suggestions/view-model';
import './preview.css';
const sampleForm:CheckinForm={state:'少し疲れている',wishes:'静かなところで休みたい',time:'30',mode:'walking',companion:'solo',effort:'easy'};
const samples:CandidateView[]=[{id:'display-cafe',title:'森のテラスカフェ',tags:['カフェ','静かな雰囲気','緑が見える'],reason:'落ち着いた空間でゆっくり過ごせます。窓から緑が見え、ひとりでも心地よく過ごせます。',wishes:'少し疲れている・静かなところで休みたい',evaluation:'未評価',travel:'徒歩8分',stay:'12分',total:'約20分',status:'',photos:[],confirmed:['カフェとして営業している','屋内の座席がある','窓から緑が見える','徒歩でアクセス可能'],unknown:['混雑状況は不明','静けさの程度は不明','現在の営業時間は要確認'],sourceUrl:null,sourceLabel:'',fetchedAt:'',expiresAt:'',memo:'',bookmarked:false},{id:'display-park',title:'東山の森公園',tags:['公園','自然を感じる','静か'],reason:'木々に囲まれた公園で、ゆったりとした時間を過ごせます。ベンチで休憩できます。',wishes:sampleForm.wishes,evaluation:'未評価',travel:'徒歩12分',stay:'15分',total:'約27分',status:'',photos:[],confirmed:[],unknown:['現在情報は未取得'],sourceUrl:null,sourceLabel:'',fetchedAt:'',expiresAt:'',memo:'',bookmarked:false}];
const samplePhotos=[{id:'sample-photo-1',url:'https://images.unsplash.com/photo-1728761390316-935ffeb3fbcc?auto=format&fit=crop&w=900&q=80',alt:'写真表示サンプル：窓辺のカフェ（Unsplash）'},{id:'sample-photo-2',url:'https://images.unsplash.com/photo-1571818462722-953fe051dd8f?auto=format&fit=crop&w=900&q=80',alt:'写真表示サンプル：植物のあるカフェ（Dick Hoogerdijk / Unsplash）'}];
function Preview(){
 const params=new URLSearchParams(location.search);const [page,setPage]=useState(params.get('page')||'all');const [form,setForm]=useState(sampleForm);const [items,setItems]=useState(samples);const [selected,setSelected]=useState(samples[0]);const [notice,setNotice]=useState<Notice|null>(null);const [sort,setSort]=useState('recommended');const [large,setLarge]=useState(false);
 useEffect(()=>{document.documentElement.style.fontSize=large?'32px':'16px';},[large]);
 const report=(text:string)=>setNotice({kind:'info',text:`表示検査のみ：${text}。API保存は行っていません。`});
 return <><aside className="qa-controls"><strong>表示サンプル · API未接続</strong><select aria-label="確認する画面" value={page} onChange={e=>setPage(e.target.value)}><option value="all">3画面を並べる</option><option value="checkin">希望入力</option><option value="list">候補一覧</option><option value="detail">候補詳細</option></select><button onClick={()=>{setItems([]);setPage('list');setNotice(null);}}>0件</button><button onClick={()=>{setItems(Array.from({length:5},(_,i)=>({...samples[i%2],id:`display-${i}`,title:i===0?'駅から歩いて行ける木々に囲まれた長い名前のテラスカフェ':samples[i%2].title,evaluation:i===1?'評価 1':'未評価'})));setPage('list');setNotice(null);}}>5件・長い名前</button><button onClick={()=>{setItems(samples);setNotice({kind:'error',text:'テストの通信失敗。入力を保持しています。',retry:()=>setNotice(null)});}}>通信失敗</button><button onClick={()=>{const next=samples.map(item=>({...item,photos:samplePhotos}));setItems(next);setSelected(next[0]);setPage('detail');setNotice(null);}}>写真あり</button><button onClick={()=>setLarge(v=>!v)}>文字200%</button><a href="https://unsplash.com/photos/j6ERcKXdlXw" target="_blank" rel="noreferrer">写真サンプル出典</a></aside>
 <main className={`qa-pages ${page!=='all'?'qa-single':''} ${large?'qa-large':''}`}>
 {(page==='all'||page==='checkin')&&<article className="sg-shell-content"><FeatureHeader title="タイプ診断" onBack={()=>setPage('all')}/><div className="qa-content"><CheckinView form={form} onChange={(key,value)=>setForm(old=>({...old,[key]:value}))} date="2026-09-15（表示例）" busy={false} notice={notice} onSave={()=>report('回答だけ保存')} onSearch={()=>{setPage('list');setNotice(null);}} onSkip={()=>report('未回答で地図へ')}/></div></article>}
 {(page==='all'||page==='list')&&<article className="sg-shell-content"><FeatureHeader title="候補を選ぶ" onBack={()=>setPage('checkin')}><button className="sg-header-condition" onClick={()=>setPage('checkin')}><Icon name="sliders"/>条件を変更</button></FeatureHeader><div className="qa-content"><SuggestionsView form={form} items={items} sort={sort} onSort={setSort} onConditions={()=>setPage('checkin')} onOpen={id=>{setSelected(items.find(item=>item.id===id)!);setPage('detail');setNotice(null);}} notice={notice} busy={false} hasBatch onMore={undefined}/></div></article>}
 {(page==='all'||page==='detail')&&<article className="sg-shell-content"><FeatureHeader title="候補の詳細" onBack={()=>setPage('list')}><button aria-label="共有する" onClick={()=>report('共有')}><Icon name="share"/></button><button aria-label="しおり" onClick={()=>report('しおり')}><Icon name="heart"/></button></FeatureHeader><div className="qa-content"><SuggestionDetailView showTools={false} item={selected} busy={false} notice={notice} onSelect={()=>report('これにする')} onLater={()=>report('後で考える')} onDismiss={()=>report('見送り')} onBookmark={()=>report('しおり')} onShare={()=>report('共有')} onMemo={value=>report(`メモ「${value}」`)} onStop={()=>report('提案停止')} onRoute={()=>report('経路へ')} onVisit={()=>report('訪問確認へ')}/></div></article>}
 </main></>;
}
createRoot(document.getElementById('root')!).render(<Preview/>);
