import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {DiscoveryView} from '../../../src/features/exploration/discovery';
import {TransferView} from '../../../src/features/transfer/views';
import {AiConsentView,VoiceConsultationView,ConversationHistoryView,MistDetailView,QuestCompassView,CandidateCard,ConsultationIntroduction} from '../../../src/features/exploration/views';
import type {PlacePresentation} from '../../../src/features/exploration/view-types';
import '../../../src/features/exploration/exploration.css';
const place:PlacePresentation={id:'preview-bookshop',name:'ひとやすみ書店',address:'名古屋市千種区山手通 3丁目12-5',coordinates:[136.965,35.17],photos:[],reason:'本を楽しみたいという希望からこの場所を提案しています。',entrance:'東側の通りに面した木の扉',source:{title:'まちの本屋さんマップ（表示例）',url:null}};
const pages=['ai-explore','voice-consultation','conversation-history','ai-consent','mist-detail','quest-compass','discovery','experience-transfer'];
const names=['Codexと探索','声で相談','相談履歴','AIを使う前に','もやの探索候補','コンパスで探す','見方をひらく','別の街で試す'];
const transferInitial={name:'名古屋の本屋から水辺へ',sourceRecordId:'example-record',sequenceReason:'刺激を得たあとに落ち着く',roles:[{key:'reading',label:'本屋で刺激を得る',purpose:'読書',reason:'新しい考えを持ち帰る',sourcePlaceName:'ひとやすみ書店',required:'静かな空間',changeable:'店舗名、広さ',memory:'友人と話した、その日の思い出',stayMinutes:'20'},{key:'rest',label:'水辺で落ち着く',purpose:'休憩',reason:'景色を見て考えを整理する',sourcePlaceName:'山崎川',required:'座れる場所',changeable:'川や池の種類',memory:'',stayMinutes:'15'}],city:'東京',desire:'静かに本を読みたい',timeMinutes:'90',costYen:'2000',requireOpen:true};
const discoveryCard={id:'example-discovery',anchor:{kind:'place' as const,targetId:'preview-bookshop',features:['赤と白の四角いタイルが交互に並んでいる']},bridge:'同じ形が繰り返される模様は、街の景色を数学へつなぐ入口になります。',knowledge:'平面を隙間なく埋める配置を、平面充填と呼びます。',observationPrompt:'タイルの角が一つの点にいくつ集まっているか、見てみましょう。',conceptIds:[],sources:[{url:null,title:'一般知識の出典を表示する位置（表示例）',claimScope:'general' as const,sourceId:null}],createdAt:Date.now()};
function App(){const [transferDraft,setTransferDraft]=useState(transferInitial);const [dirty,setDirty]=useState(false);const [selectedPlan,setSelectedPlan]=useState('faithful');const [discoveryFeature,setDiscoveryFeature]=useState(discoveryCard.anchor.features[0]);const [discoveryKind,setDiscoveryKind]=useState<'place'|'building'|'photo'>('place');const [discoveryTarget,setDiscoveryTarget]=useState('preview-bookshop');const [discoveryMode,setDiscoveryMode]=useState<'explore'|'saved'>('explore');const [notice,setNotice]=useState<string|null>(null);const params=new URLSearchParams(location.search);const [page,setPage]=useState(params.get('page')??'voice-consultation');const [text,setText]=useState('静かな場所を探したい');const [enabled,setEnabled]=useState(false);const [selected,setSelected]=useState<PlacePresentation|null>(place);const [query,setQuery]=useState('');const [saved,setSaved]=useState(false);const [recording,setRecording]=useState(true);const [sent,setSent]=useState(0);const [headingState,setHeadingState]=useState<'idle'|'denied'>('idle');const history=[{id:'h1',title:'30分の寄り道',preview:'本山駅の近くで、仕事の合間に30分だけ立ち寄れる場所を…',updatedAt:Date.now(),tags:['本山駅','散歩','リフレッシュ']},{id:'h2',title:'ひとりでカフェに行きたい',preview:'落ち着いて作業できるカフェを教えてください。',updatedAt:Date.now()-60*60000,tags:['カフェ','ひとり時間','作業']},{id:'h3',title:'雨の日に本山で過ごす',preview:'雨の日でも楽しめる本山エリアの過ごし方を知りたいです。',updatedAt:Date.now()-86400000,tags:['雨の日','本山','屋内スポット']},{id:'h4',title:'本屋さんをめぐりたい',preview:'本山の個性的な本屋さんをいくつか教えてください。',updatedAt:Date.now()-90000000,tags:['本屋','散策','カルチャー']}];
return <><style>{`html{font-size:${params.get('large-text')==='1'?'32px':'16px'}}*{box-sizing:border-box}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,'Hiragino Kaku Gothic ProN',sans-serif;font-size:1rem;color:#12394a;background:#f1f8f8}button,input,textarea{font:inherit}button{cursor:pointer}.preview-toolbar{position:fixed;top:0;left:420px;padding:12px;display:grid;gap:8px}.preview-toolbar button{background:white;color:#17656c;padding:8px;border:1px solid #c7dfe1;border-radius:8px}.preview-frame{max-width:420px;margin:0 auto;min-height:100dvh}.preview-heading{height:62px;padding:15px 16px;display:flex;align-items:center;justify-content:space-between}.preview-heading h1{font-size:17px;margin:0}.preview-heading button{background:transparent;border:0;color:inherit;font-size:24px}.preview-mock{font-size:11px;text-align:right;margin:0;padding:4px 14px;color:#698391}.preview-map-missing{height:100%;display:grid;place-items:center;color:#5a7985;background:#eaf1f4;font-size:12px}.preview-conversation{padding:12px}.preview-user{margin-left:80px;background:#e0efee;border-radius:18px;padding:12px;font-size:15px}.preview-assistant{background:white;padding:14px;border-radius:18px;font-size:15px;line-height:1.7}.preview-composer{display:flex;gap:10px;background:white;padding:10px;border-radius:28px;position:sticky;bottom:0;box-shadow:0 -2px 12px #34545711}.preview-composer textarea{width:100%;border:0;border-radius:20px;padding:8px;resize:none}.preview-composer button{border:0;background:#32abaa;color:white;border-radius:50%;min-width:44px}@media(min-width:850px){.preview-frame{margin-left:0}}@media(max-width:849px){.preview-toolbar{display:none}}`}</style><nav className="preview-toolbar">{pages.map((p,i)=><button key={p} onClick={()=>setPage(p)}>{names[i]}</button>)}<output>送信確定 {sent} 回</output><p>表示例の操作検査。API保存なし。</p></nav><main className="preview-frame"><header className="preview-heading"><button aria-label="戻る" onClick={()=>setPage('ai-explore')}>‹</button><h1>{names[pages.indexOf(page)]}</h1><button aria-label="メニュー">☰</button></header><p className="preview-mock">表示例・通信なし・写真は未取得</p>
{page==='voice-consultation'&&<VoiceConsultationView voice={{state:recording?'recording':'stopped',seconds:8,levels:Array.from({length:40},(_,i)=>.1+Math.abs(Math.sin(i*1.7)*Math.sin(i*.23))*.75),error:null,transcript:text}} onStart={()=>setRecording(true)} onStop={()=>setRecording(false)} onChange={setText} onClear={()=>setText('')} onSend={()=>setPage('ai-consent')} onRetry={()=>{}}/>}
{page==='ai-consent'&&<AiConsentView text={text} enabled={enabled} place={selected} busy={false} error={null} onText={setText} onEnable={setEnabled} onChangePlace={()=>setSelected(place)} onRemovePlace={()=>setSelected(null)} onCancel={()=>setPage('voice-consultation')} onSend={()=>{setSent(x=>x+1);setPage('ai-explore')}}/>}
{page==='conversation-history'&&<ConversationHistoryView conversations={history.filter(h=>(h.title+h.preview).includes(query))} query={query} busy={false} error={null} hasMore={false} onSearch={setQuery} onOpen={()=>setPage('ai-explore')} onNew={()=>{setText('');setPage('ai-explore')}} onMore={()=>{}} onRetry={()=>{}}/>}
{page==='mist-detail'&&<MistDetailView place={place} bookmarked={saved} expired={false} busy={false} error={null} onBookmark={()=>setSaved(!saved)} onWalk={()=>{}} onCompass={()=>setPage('quest-compass')} onSearchAgain={()=>setPage('ai-explore')} onRetry={()=>{}} mapPreview={<div className="preview-map-missing">共通MapRenderer接続待ち</div>}/>}
{page==='quest-compass'&&<QuestCompassView place={place} position={{coordinates:[136.965,35.16892],accuracy:6,timestamp:Date.now()}} positionError={null} stale={false} heading={null} headingState={headingState} onEnableHeading={()=>setHeadingState('denied')} onRoute={()=>{}} onEnd={()=>setPage('mist-detail')}/>}
{page==='ai-explore'&&<div className="preview-conversation"><ConsultationIntroduction/><p className="preview-user">静かなカフェに寄って、30分くらい散歩したい</p><p className="preview-assistant">本山周辺の候補です。<br/>静かなカフェでひと息ついた後に、緑のある道を歩く約30分のコースをご提案します。</p><CandidateCard place={{...place,id:'cafe-example',name:'cafe mois（カフェ モア）',category:'カフェ',description:'ひと息つけるカフェ',reason:'住宅街にある静かなカフェ。大きな窓から緑が見え、ゆっくりと過ごせます。',walkingMinutes:8,stayMinutes:12}} index={0} selected={false} expired={false} busy={false} onShowMap={()=>setPage('mist-detail')} journeyTotal={{walkingMinutes:18,stayMinutes:12}} onDetail={()=>setPage('mist-detail')} onSearchAgain={()=>{}} mapPreview={<div className="preview-map-missing">共通MapRenderer接続待ち</div>}/><CandidateCard place={{...place,id:'park-example',name:'東山公園',category:'公園'}} index={1} selected={false} expired={false} busy={false} onShowMap={()=>{}} onDetail={()=>{}} onSearchAgain={()=>{}}/><form className="preview-composer" onSubmit={e=>{e.preventDefault();setPage('ai-consent')}}><textarea value={text} rows={1} placeholder="Codexに話しかける…" onChange={e=>setText(e.target.value)}/><button aria-label="送信">↑</button></form></div>}
{page==='discovery'&&<DiscoveryView mode={discoveryMode} kind={discoveryKind} targetId={discoveryTarget} feature={discoveryFeature} targets={[{id:'preview-bookshop',label:'ひとやすみ書店'}]} card={discoveryCard} saved={[discoveryCard]} busy={false} error={null} notice={notice} onKind={setDiscoveryKind} onTarget={setDiscoveryTarget} onFeature={setDiscoveryFeature} onOpen={()=>setNotice('表示例です。API保存は行っていません。')} onSaved={()=>setDiscoveryMode('saved')} onReopen={()=>setDiscoveryMode('explore')} onReaction={reaction=>setNotice(`表示例の操作: ${reaction}。保存なし。`)} onRetry={()=>{}}/>}
{page==='experience-transfer'&&<TransferView draft={transferDraft} records={[{id:'example-record',label:'名古屋の本屋から水辺へ'}]} plans={(['faithful','personal'] as const).map(mode=>({id:mode,mode,label:mode==='faithful'?'元の意味と順番を保つ案':'静かな読書を長めにする案',status:'表示例',adoptable:true,roles:transferInitial.roles.map((r,i)=>({key:r.key,originalLabel:r.label,originalReason:r.reason,placeName:i===0?'次の街の本屋（表示例）':'川沿いの公園（表示例）',retained:[r.reason],changed:['場所が変わります'],nonTransferable:r.memory?[r.memory]:[],unknown:['営業情報は未確認です']})),warnings:[]}))} selectedId={selectedPlan} savedItems={[]} dirty={dirty} busy={false} error={null} notice={notice} onDraft={next=>{setTransferDraft(next);setDirty(true)}} onAddRole={()=>{setTransferDraft(d=>({...d,roles:[...d.roles,{...d.roles[0],key:`stage-${d.roles.length}`,label:''}]}));setDirty(true)}} onRemoveRole={key=>{setTransferDraft(d=>({...d,roles:d.roles.filter(r=>r.key!==key)}));setDirty(true)}} onMoveRole={key=>{setTransferDraft(d=>{const list=[...d.roles];const i=list.findIndex(r=>r.key===key);if(i>0)[list[i-1],list[i]]=[list[i],list[i-1]];return {...d,roles:list}});setDirty(true)}} onSave={()=>{setDirty(false);setNotice('表示例です。API保存は行っていません。')}} onCompare={()=>setNotice('リハーサルの構成に基づく二案の表示例です。')} onSelect={setSelectedPlan} onAdopt={()=>setNotice('採用ボタンの操作確認です。API保存は行っていません。')} onDefer={()=>setNotice('後でボタンの操作確認です。API保存は行っていません。')} onReopen={()=>{}} onRetry={()=>{}}/>}
</main></>};createRoot(document.getElementById('root')!).render(<App/>);
