-- Generated by tools/local/build-base.py from docs/01_requirements/01_DB.

-- Ownership, JSON references and business transitions are checked by feature services.

CREATE TABLE people (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  name TEXT NOT NULL,
  bio TEXT NOT NULL,
  avatar_path TEXT,
  CHECK(updated_at >= created_at)
) STRICT;

CREATE TABLE places (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  name TEXT NOT NULL,
  longitude REAL NOT NULL,
  latitude REAL NOT NULL,
  address TEXT,
  provider TEXT NOT NULL,
  external_id TEXT,
  building_key TEXT,
  source_url TEXT,
  attribution TEXT NOT NULL,
  fetched_at INTEGER,
  CHECK(updated_at >= created_at),
  UNIQUE(provider, external_id),
  CHECK(longitude BETWEEN -180 AND 180),
  CHECK(latitude BETWEEN -90 AND 90)
) STRICT;

CREATE TABLE records (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  kind TEXT NOT NULL CHECK(kind IN ('experience', 'diary', 'memo')),
  visit_id TEXT REFERENCES visits(id) ON DELETE SET NULL,
  place_id TEXT REFERENCES places(id) ON DELETE RESTRICT,
  occurred_at INTEGER,
  ended_at INTEGER,
  time_precision TEXT NOT NULL CHECK(time_precision IN ('exact', 'approximate', 'unknown')),
  body TEXT NOT NULL,
  purposes_json TEXT NOT NULL CHECK(json_valid(purposes_json) AND json_type(purposes_json)='array'),
  activities_json TEXT NOT NULL CHECK(json_valid(activities_json) AND json_type(activities_json)='array'),
  impression TEXT NOT NULL,
  period_answers_json TEXT NOT NULL CHECK(json_valid(period_answers_json) AND json_type(period_answers_json)='object'),
  bookmarked INTEGER NOT NULL CHECK(bookmarked IN (0, 1)),
  use_for_suggestions INTEGER NOT NULL CHECK(use_for_suggestions IN (0, 1)),
  topic_key TEXT,
  visibility TEXT NOT NULL CHECK(visibility IN ('private', 'selected', 'public')),
  shared_with_json TEXT NOT NULL CHECK(json_valid(shared_with_json) AND json_type(shared_with_json)='array'),
  CHECK(updated_at >= created_at),
  CHECK(ended_at IS NULL OR (occurred_at IS NOT NULL AND ended_at >= occurred_at)),
  CHECK(time_precision != 'unknown' OR (occurred_at IS NULL AND ended_at IS NULL)),
  CHECK(visit_id IS NULL OR (kind='experience' AND place_id IS NULL AND occurred_at IS NULL AND ended_at IS NULL AND time_precision='unknown')),
  CHECK((visibility='selected' AND json_array_length(shared_with_json)>0) OR (visibility!='selected' AND json_array_length(shared_with_json)=0))
) STRICT;

CREATE INDEX records_idx_0 ON records(person_id, occurred_at);

CREATE INDEX records_idx_1 ON records(visit_id);

CREATE INDEX records_idx_2 ON records(visibility, topic_key);

CREATE INDEX records_idx_3 ON records(place_id);

CREATE TABLE media (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  record_id TEXT NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  storage_key TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('photo', 'video', 'audio')),
  mime_type TEXT NOT NULL,
  byte_size INTEGER NOT NULL,
  position INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pending', 'ready', 'failed')),
  CHECK(updated_at >= created_at),
  UNIQUE(storage_key),
  UNIQUE(record_id, position),
  CHECK(byte_size >= 0),
  CHECK(position >= 0)
) STRICT;

CREATE TABLE conversations (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  purpose TEXT NOT NULL CHECK(purpose IN ('consult', 'reflection', 'analysis', 'comparison')),
  title TEXT NOT NULL,
  record_id TEXT REFERENCES records(id) ON DELETE SET NULL,
  CHECK(updated_at >= created_at)
) STRICT;

CREATE INDEX conversations_idx_0 ON conversations(person_id, updated_at);

CREATE INDEX conversations_idx_1 ON conversations(record_id);

CREATE TABLE messages (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
  body TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pending', 'running', 'complete', 'failed', 'cancelled')),
  attempt INTEGER NOT NULL,
  model TEXT,
  error_code TEXT,
  insight_id TEXT REFERENCES insights(id) ON DELETE SET NULL,
  source_refs_json TEXT NOT NULL CHECK(json_valid(source_refs_json) AND json_type(source_refs_json)='array'),
  CHECK(updated_at >= created_at),
  CHECK(role != 'user' OR (status='complete' AND model IS NULL)),
  CHECK(position >= 0),
  CHECK(attempt >= 0)
) STRICT;

CREATE UNIQUE INDEX messages_idx_0 ON messages(conversation_id, position);

CREATE TABLE saved_routes (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  waypoints_json TEXT NOT NULL CHECK(json_valid(waypoints_json) AND json_type(waypoints_json)='array'),
  route_json TEXT NOT NULL CHECK(json_valid(route_json) AND json_type(route_json)='object'),
  distance_m REAL,
  duration_sec INTEGER,
  provider TEXT,
  source_url TEXT,
  fetched_at INTEGER,
  status TEXT NOT NULL CHECK(status IN ('saved', 'navigating', 'finished')),
  current_leg INTEGER NOT NULL,
  visibility TEXT NOT NULL CHECK(visibility IN ('private', 'selected', 'public')),
  shared_with_json TEXT NOT NULL CHECK(json_valid(shared_with_json) AND json_type(shared_with_json)='array'),
  CHECK(updated_at >= created_at),
  CHECK(json_array_length(waypoints_json) >= 2),
  CHECK(current_leg >= 0),
  CHECK(distance_m IS NULL OR distance_m >= 0),
  CHECK(duration_sec IS NULL OR duration_sec >= 0),
  CHECK((visibility='selected' AND json_array_length(shared_with_json)>0) OR (visibility!='selected' AND json_array_length(shared_with_json)=0))
) STRICT;

CREATE INDEX saved_routes_idx_0 ON saved_routes(person_id, updated_at);

CREATE TABLE plugin_settings (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  enabled INTEGER NOT NULL CHECK(enabled IN (0, 1)),
  settings_json TEXT NOT NULL CHECK(json_valid(settings_json) AND json_type(settings_json)='object'),
  CHECK(updated_at >= created_at)
) STRICT;

CREATE TABLE feature_requests (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  visibility TEXT NOT NULL CHECK(visibility IN ('private', 'public')),
  CHECK(updated_at >= created_at)
) STRICT;

CREATE INDEX feature_requests_idx_0 ON feature_requests(visibility, created_at);

CREATE INDEX feature_requests_idx_1 ON feature_requests(person_id);

CREATE TABLE track_points (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  segment_id TEXT NOT NULL,
  source_point_id TEXT NOT NULL,
  observed_at INTEGER NOT NULL,
  longitude REAL NOT NULL,
  latitude REAL NOT NULL,
  accuracy_m REAL NOT NULL,
  CHECK(updated_at >= created_at),
  UNIQUE(person_id, source_point_id),
  CHECK(longitude BETWEEN -180 AND 180),
  CHECK(latitude BETWEEN -90 AND 90),
  CHECK(accuracy_m >= 0)
) STRICT;

CREATE INDEX track_points_idx_0 ON track_points(person_id, observed_at);

CREATE TABLE transit_passes (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  operator TEXT NOT NULL,
  segments_json TEXT NOT NULL CHECK(json_valid(segments_json) AND json_type(segments_json)='array'),
  valid_from TEXT NOT NULL,
  valid_to TEXT NOT NULL,
  CHECK(updated_at >= created_at),
  CHECK(valid_to >= valid_from),
  CHECK(json_array_length(segments_json) > 0)
) STRICT;

CREATE INDEX transit_passes_idx_0 ON transit_passes(person_id);

CREATE TABLE self_checkins (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  local_date TEXT NOT NULL,
  answers_json TEXT NOT NULL CHECK(json_valid(answers_json) AND json_type(answers_json)='object'),
  valid_until INTEGER NOT NULL,
  CHECK(updated_at >= created_at),
  CHECK(valid_until > created_at)
) STRICT;

CREATE INDEX self_checkins_idx_0 ON self_checkins(person_id, local_date, created_at);

CREATE TABLE suggestions (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  place_id TEXT NOT NULL REFERENCES places(id) ON DELETE RESTRICT,
  batch_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  title TEXT NOT NULL,
  activity TEXT NOT NULL,
  reason TEXT NOT NULL,
  conditions_json TEXT NOT NULL CHECK(json_valid(conditions_json) AND json_type(conditions_json)='object'),
  checkin_id TEXT REFERENCES self_checkins(id) ON DELETE SET NULL,
  source_refs_json TEXT NOT NULL CHECK(json_valid(source_refs_json) AND json_type(source_refs_json)='array'),
  status TEXT NOT NULL CHECK(status IN ('offered', 'later', 'dismissed', 'selected', 'completed', 'not_done')),
  presented_at INTEGER,
  selected_at INTEGER,
  expires_at INTEGER NOT NULL,
  route_id TEXT REFERENCES saved_routes(id) ON DELETE SET NULL,
  completed_visit_id TEXT REFERENCES visits(id) ON DELETE RESTRICT,
  feedback TEXT NOT NULL,
  CHECK(updated_at >= created_at),
  UNIQUE(person_id, batch_id, position),
  CHECK(position >= 0),
  CHECK(expires_at > created_at),
  CHECK((status='completed') = (completed_visit_id IS NOT NULL))
) STRICT;

CREATE INDEX suggestions_idx_0 ON suggestions(person_id, status);

CREATE INDEX suggestions_idx_1 ON suggestions(place_id);

CREATE INDEX suggestions_idx_2 ON suggestions(checkin_id);

CREATE INDEX suggestions_idx_3 ON suggestions(route_id);

CREATE INDEX suggestions_idx_4 ON suggestions(completed_visit_id);

CREATE TABLE themes (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  record_ids_json TEXT NOT NULL CHECK(json_valid(record_ids_json) AND json_type(record_ids_json)='array'),
  CHECK(updated_at >= created_at)
) STRICT;

CREATE INDEX themes_idx_0 ON themes(person_id);

CREATE TABLE friendships (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  requester_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  recipient_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK(status IN ('pending', 'accepted')),
  CHECK(updated_at >= created_at),
  CHECK(requester_id != recipient_id)
) STRICT;

CREATE UNIQUE INDEX friendships_idx_0 ON friendships(min(requester_id, recipient_id), max(requester_id, recipient_id));

CREATE INDEX friendships_idx_1 ON friendships(recipient_id, status);

CREATE TABLE visits (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  place_id TEXT NOT NULL REFERENCES places(id) ON DELETE RESTRICT,
  started_at INTEGER,
  ended_at INTEGER,
  time_precision TEXT NOT NULL CHECK(time_precision IN ('exact', 'approximate', 'unknown')),
  origin TEXT NOT NULL CHECK(origin IN ('manual', 'gps')),
  status TEXT NOT NULL CHECK(status IN ('candidate', 'confirmed', 'rejected')),
  CHECK(updated_at >= created_at),
  CHECK(ended_at IS NULL OR (started_at IS NOT NULL AND ended_at >= started_at)),
  CHECK(time_precision != 'unknown' OR (started_at IS NULL AND ended_at IS NULL))
) STRICT;

CREATE INDEX visits_idx_0 ON visits(person_id, place_id, status);

CREATE INDEX visits_idx_1 ON visits(person_id, started_at);

CREATE TABLE insights (
  id TEXT NOT NULL PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version >= 1),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  person_id TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  kind TEXT NOT NULL CHECK(kind IN ('analysis', 'comparison')),
  input_key TEXT NOT NULL,
  source_refs_json TEXT NOT NULL CHECK(json_valid(source_refs_json) AND json_type(source_refs_json)='array'),
  range_start INTEGER,
  range_end INTEGER,
  timezone TEXT NOT NULL,
  generator_version TEXT NOT NULL,
  model TEXT,
  summary TEXT NOT NULL,
  result_json TEXT NOT NULL CHECK(json_valid(result_json)),
  review TEXT CHECK(review IN ('agree', 'disagree', 'unsure', 'edit')),
  review_note TEXT,
  reviewed_at INTEGER,
  CHECK(updated_at >= created_at),
  CHECK(kind!='analysis' OR (range_start IS NOT NULL AND range_end IS NOT NULL)),
  CHECK((range_start IS NULL AND range_end IS NULL) OR (range_start IS NOT NULL AND range_end IS NOT NULL AND range_end > range_start)),
  CHECK(review IS NULL OR reviewed_at IS NOT NULL)
) STRICT;

CREATE UNIQUE INDEX insights_idx_0 ON insights(person_id, kind, input_key);

CREATE INDEX insights_idx_1 ON insights(person_id, created_at);

-- Approved common storage additions, in this migration transaction.

-- 既存のpeople/places/messages等を作成した後、一度だけ適用する。

-- JSON内容と対象所有者は本文の共通処理でも検査する。

ALTER TABLE places ADD COLUMN categories_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(categories_json) AND json_type(categories_json)='array');

ALTER TABLE messages ADD COLUMN task TEXT;

ALTER TABLE messages ADD COLUMN request_hash TEXT;

ALTER TABLE messages ADD COLUMN request_json TEXT CHECK(request_json IS NULL OR json_valid(request_json));

ALTER TABLE messages ADD COLUMN result_json TEXT CHECK(result_json IS NULL OR json_valid(result_json));

ALTER TABLE messages ADD COLUMN applied_refs_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(applied_refs_json) AND json_type(applied_refs_json)='array');

CREATE UNIQUE INDEX common_one_active_run ON messages(conversation_id) WHERE role='assistant' AND status IN ('pending','running');

CREATE TABLE creation_receipts (

 person_id TEXT NOT NULL REFERENCES people(id),

 operation TEXT NOT NULL CHECK(operation IN ('place-adopt','route-save')),

 target_id TEXT NOT NULL,

 input_hash TEXT NOT NULL,

 result_type TEXT NOT NULL CHECK(result_type IN ('place','route')),

 result_id TEXT NOT NULL,

 created_at INTEGER NOT NULL,

 PRIMARY KEY(person_id,operation,target_id),

 CHECK((operation='place-adopt' AND result_type='place') OR (operation='route-save' AND result_type='route'))

);

CREATE TABLE discovery_cards (

 id TEXT PRIMARY KEY NOT NULL,

 person_id TEXT NOT NULL REFERENCES people(id),

 anchor_json TEXT NOT NULL CHECK(json_valid(anchor_json)),

 bridge TEXT NOT NULL,

 knowledge TEXT NOT NULL,

 observation_prompt TEXT NOT NULL,

 concept_ids_json TEXT NOT NULL CHECK(json_valid(concept_ids_json)),

 sources_json TEXT NOT NULL CHECK(json_valid(sources_json)),

 source_refs_json TEXT NOT NULL CHECK(json_valid(source_refs_json)),

 version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1),

 created_at INTEGER NOT NULL,

 updated_at INTEGER NOT NULL CHECK(updated_at>=created_at)

);

CREATE INDEX discovery_cards_owner ON discovery_cards(person_id,updated_at);

CREATE TABLE discovery_reactions (

 id TEXT PRIMARY KEY NOT NULL,

 person_id TEXT NOT NULL REFERENCES people(id),

 card_id TEXT NOT NULL REFERENCES discovery_cards(id) ON DELETE CASCADE,

 reaction TEXT NOT NULL CHECK(reaction IN ('known','interested','saved','blocked','dismissed')),

 created_at INTEGER NOT NULL

);

CREATE INDEX discovery_reactions_latest ON discovery_reactions(card_id,created_at,id);
