"""Materialize the 17 documented base tables; feature additions stay feature-owned."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / 'docs/01_requirements/01_DB'
common = json.loads((SPEC / 'common.json').read_text())['columns']


def literal(value):
    return str(value) if isinstance(value, int) else "'" + value.replace("'", "''") + "'"


checks = {
    'places': ['UNIQUE(provider, external_id)', 'CHECK(longitude BETWEEN -180 AND 180)', 'CHECK(latitude BETWEEN -90 AND 90)'],
    'records': [
        'CHECK(ended_at IS NULL OR (occurred_at IS NOT NULL AND ended_at >= occurred_at))',
        "CHECK(time_precision != 'unknown' OR (occurred_at IS NULL AND ended_at IS NULL))",
        "CHECK(visit_id IS NULL OR (kind='experience' AND place_id IS NULL AND occurred_at IS NULL AND ended_at IS NULL AND time_precision='unknown'))",
        "CHECK((visibility='selected' AND json_array_length(shared_with_json)>0) OR (visibility!='selected' AND json_array_length(shared_with_json)=0))",
    ],
    'media': ['UNIQUE(storage_key)', 'UNIQUE(record_id, position)', 'CHECK(byte_size >= 0)', 'CHECK(position >= 0)'],
    'messages': ["CHECK(role != 'user' OR (status='complete' AND model IS NULL))", 'CHECK(position >= 0)', 'CHECK(attempt >= 0)'],
    'saved_routes': [
        'CHECK(json_array_length(waypoints_json) >= 2)', 'CHECK(current_leg >= 0)',
        'CHECK(distance_m IS NULL OR distance_m >= 0)', 'CHECK(duration_sec IS NULL OR duration_sec >= 0)',
        "CHECK((visibility='selected' AND json_array_length(shared_with_json)>0) OR (visibility!='selected' AND json_array_length(shared_with_json)=0))",
    ],
    'track_points': ['UNIQUE(person_id, source_point_id)', 'CHECK(longitude BETWEEN -180 AND 180)', 'CHECK(latitude BETWEEN -90 AND 90)', 'CHECK(accuracy_m >= 0)'],
    'transit_passes': ['CHECK(valid_to >= valid_from)', 'CHECK(json_array_length(segments_json) > 0)'],
    'self_checkins': ['CHECK(valid_until > created_at)'],
    'suggestions': ['UNIQUE(person_id, batch_id, position)', 'CHECK(position >= 0)', 'CHECK(expires_at > created_at)', "CHECK((status='completed') = (completed_visit_id IS NOT NULL))"],
    'friendships': ['CHECK(requester_id != recipient_id)'],
    'visits': ['CHECK(ended_at IS NULL OR (started_at IS NOT NULL AND ended_at >= started_at))', "CHECK(time_precision != 'unknown' OR (started_at IS NULL AND ended_at IS NULL))"],
    'insights': ["CHECK(kind!='analysis' OR (range_start IS NOT NULL AND range_end IS NOT NULL))", 'CHECK((range_start IS NULL AND range_end IS NULL) OR (range_start IS NOT NULL AND range_end IS NOT NULL AND range_end > range_start))', 'CHECK(review IS NULL OR reviewed_at IS NOT NULL)'],
}
out = ['-- Generated by tools/local/build-base.py from docs/01_requirements/01_DB.',
       '-- Ownership, JSON references and business transitions are checked by feature services.']
for source in sorted(SPEC.glob('[0-9]*.json')):
    spec = json.loads(source.read_text())
    table = spec['table']
    columns = {**common, **spec['columns']}
    defs = []
    for name, col in columns.items():
        definition = f'{name} {col["type"]}'
        if not col.get('nullable', True):
            definition += ' NOT NULL'
        if name == 'id':
            definition += ' PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 80 AND length(trim(id)) > 0)'
        if name == 'version':
            definition += ' DEFAULT 1 CHECK(version >= 1)'
        if col.get('enum'):
            definition += f' CHECK({name} IN ({", ".join(map(literal, col["enum"]))}))'
        if col.get('encoding') == 'json':
            shape = spec.get('json_fields', {}).get(name, {})
            root = shape.get('fields', {}).get('$', {}).get('type')
            if '$ref' in shape:
                root = 'array'
            definition += f' CHECK(json_valid({name})' + (f" AND json_type({name})='{root}'" if root in ('array', 'object') else '') + ')'
        ref = spec.get('references', {}).get(name)
        if ref:
            target_table, target_column = ref['target'].split('.')
            policy = ref.get('on_delete', '')
            action = 'CASCADE' if 'この行も削除' in policy else 'SET NULL' if 'NULL' in policy and name != 'completed_visit_id' else 'RESTRICT'
            definition += f' REFERENCES {target_table}({target_column}) ON DELETE {action}'
        defs.append(definition)
    defs += ['CHECK(updated_at >= created_at)', *checks.get(table, [])]
    out.append(f'CREATE TABLE {table} (\n  ' + ',\n  '.join(defs) + '\n) STRICT;')
    for i, index in enumerate(spec.get('indexes', [])):
        cols = index['columns']
        if index.get('order_independent'):
            cols = [f'min({", ".join(cols)})', f'max({", ".join(cols)})']
        unique = 'UNIQUE ' if index.get('unique') else ''
        out.append(f'CREATE {unique}INDEX {table}_idx_{i} ON {table}({", ".join(cols)});')
additions = (ROOT / 'docs/01_requirements/02_common/references/storage-additions.sql').read_text()
out.append('-- Approved common storage additions, in this migration transaction.')
out.extend(line for line in additions.splitlines() if line.strip() not in ('BEGIN IMMEDIATE;', 'COMMIT;', 'PRAGMA foreign_keys = ON;'))
dest = ROOT / 'server/db/migrations/000-base.sql'
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text('\n\n'.join(out) + '\n')
