// Generated from the composed OpenAPI. Run bun run contracts:build.

export type Id = string;
export type Version = number;
export type Timestamp = number;
export type Date = string;
export type TimeZone = string;
export type Position = { "longitude": number; "latitude": number };
export type SourceRef = { "type": "record" | "visit" | "place" | "checkin" | "route"; "id": Id; "version": Version };
export type Person = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "name": string; "bio": string; "avatarUrl": (string | null) };
export type PersonPatch = { "name"?: string; "bio"?: string; "avatarUrl"?: (string | null) };
export type Place = { "id": string; "name": string; "address": (string | null); "coordinates": [number, number]; "categories": Array<string>; "provider": string; "externalId": (string | null); "buildingKey": (string | null); "sourceUrl": (string | null); "attribution": string; "fetchedAt": (number | null); "version": number; "createdAt": number; "updatedAt": number };
export type PlacePatch = { "name"?: string; "address"?: (string | null); "buildingKey"?: (string | null) };
export type Visit = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "placeId": Id; "startedAt": (Timestamp | null); "endedAt": (Timestamp | null); "timePrecision": "exact" | "approximate" | "unknown"; "origin": "manual" | "gps"; "status": "candidate" | "confirmed" | "rejected" };
export type VisitCreate = { "id": Id; "placeId": Id; "startedAt": (Timestamp | null); "endedAt": (Timestamp | null); "timePrecision": "exact" | "approximate" | "unknown"; "origin": "manual" | "gps" };
export type VisitPatch = { "placeId"?: Id; "startedAt"?: (Timestamp | null); "endedAt"?: (Timestamp | null); "timePrecision"?: "exact" | "approximate" | "unknown"; "status"?: "candidate" | "confirmed" | "rejected" };
export type Activity = { "id": Id; "name": string; "purpose": (string | null); "outcome": (string | null); "satisfaction": ("met" | "partial" | "not_met" | null); "repeatIntent": (boolean | null) };
export type PeriodAnswers = { "detour"?: (boolean | null); "newPlace"?: (boolean | null); "rest"?: (boolean | null); "alone"?: (boolean | null); "longStay"?: (boolean | null); "farTrip"?: (boolean | null) };
export type RecordCreate = { "id": Id; "kind": "experience" | "diary" | "memo"; "visitId": (Id | null); "placeId": (Id | null); "occurredAt": (Timestamp | null); "endedAt": (Timestamp | null); "timePrecision": "exact" | "approximate" | "unknown"; "body": string; "purposes": Array<string>; "activities": Array<Activity>; "impression": string; "periodAnswers": PeriodAnswers; "bookmarked": boolean; "useForSuggestions": boolean; "topicKey": (string | null); "visibility": "private" | "selected" | "public"; "sharedWith": Array<Id> };
export type RecordPatch = { "visitId"?: (Id | null); "placeId"?: (Id | null); "occurredAt"?: (Timestamp | null); "endedAt"?: (Timestamp | null); "timePrecision"?: "exact" | "approximate" | "unknown"; "body"?: string; "purposes"?: Array<string>; "activities"?: Array<Activity>; "impression"?: string; "periodAnswers"?: PeriodAnswers; "bookmarked"?: boolean; "useForSuggestions"?: boolean; "topicKey"?: (string | null); "visibility"?: "private" | "selected" | "public"; "sharedWith"?: Array<Id> };
export type Media = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "recordId": Id; "kind": "photo" | "video" | "audio"; "mimeType": "image/jpeg" | "image/png" | "image/webp" | "video/mp4" | "audio/mpeg" | "audio/mp4" | "audio/wav"; "byteSize": number; "position": number; "status": "pending" | "ready" | "failed"; "contentUrl": (string | null) };
export type Conversation = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "purpose": "consult" | "reflection" | "analysis" | "comparison"; "title": string; "recordId": (Id | null) };
export type ConversationCreate = { "id": Id; "purpose": "consult" | "reflection" | "analysis" | "comparison"; "title": string; "recordId": (Id | null) };
export type ConversationPatch = { "title"?: string };
export type Message = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "conversationId": Id; "position": number; "role": "user" | "assistant"; "body": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "model": (string | null); "errorCode": (string | null); "insightId": (Id | null); "sourceRefs": Array<SourceRef> };
export type SavedRoute = { "id": string; "personId": string; "title": string; "waypoints": Array<{ "coordinates": [number, number]; "name": string; "placeId": (string | null) }>; "mode": "walking" | "cycling" | "driving" | "transit"; "legs": Array<{ "fromIndex": number; "toIndex": number; "geometry": CommonMapGeometry; "distanceM": number; "durationSec": number }>; "geometry": CommonMapGeometry; "distanceM": number; "durationSec": number; "provider": "mapbox-directions"; "sourceUrl": (string | null); "fetchedAt": number; "status": "saved" | "navigating" | "finished"; "currentLeg": number; "visibility": "private" | "selected" | "public"; "sharedWith": Array<string>; "version": number; "createdAt": number; "updatedAt": number };
export type PluginValues = { [key: string]: unknown };
export type PluginSetting = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "enabled": boolean; "settings": PluginValues };
export type PluginSettingCreate = { "id": Id; "enabled": boolean; "settings": PluginValues };
export type PluginSettingPatch = { "enabled"?: boolean; "settings"?: PluginValues };
export type FeatureRequest = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "title": string; "body": string; "visibility": "private" | "public" };
export type FeatureRequestCreate = { "id": Id; "title": string; "body": string; "visibility": "private" | "public" };
export type FeatureRequestPatch = { "title"?: string; "body"?: string; "visibility"?: "private" | "public" };
export type TrackPoint = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "segmentId": Id; "sourcePointId": Id; "observedAt": Timestamp; "longitude": number; "latitude": number; "accuracyM": number };
export type TrackPointCreate = { "id": Id; "segmentId": Id; "sourcePointId": Id; "observedAt": Timestamp; "longitude": number; "latitude": number; "accuracyM": number };
export type TransitSegment = { "lineId": Id; "fromStopId": Id; "toStopId": Id };
export type TransitPass = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "operator": string; "segments": Array<TransitSegment>; "validFrom": Date; "validTo": Date };
export type TransitPassCreate = { "id": Id; "operator": string; "segments": Array<TransitSegment>; "validFrom": Date; "validTo": Date };
export type TransitPassPatch = { "operator"?: string; "segments"?: Array<TransitSegment>; "validFrom"?: Date; "validTo"?: Date };
export type CheckinAnswers = { "state": string; "wishes": Array<string>; "minutes": (number | null); "note": string };
export type SelfCheckin = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "localDate": Date; "answers": CheckinAnswers; "validUntil": Timestamp };
export type SelfCheckinCreate = { "id": Id; "localDate": Date; "answers": CheckinAnswers; "validUntil": Timestamp };
export type SelfCheckinPatch = { "localDate"?: Date; "answers"?: CheckinAnswers; "validUntil"?: Timestamp };
export type SuggestionConditions = { "minutes"?: number; "budget"?: number; "mode"?: "walking" | "cycling" | "driving" | "transit"; "activity"?: string; "note"?: string };
export type Suggestion = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "placeId": Id; "batchId": Id; "position": number; "title": string; "activity": string; "reason": string; "conditions": SuggestionConditions; "checkinId": (Id | null); "sourceRefs": Array<SourceRef>; "status": "offered" | "later" | "dismissed" | "selected" | "completed" | "not_done"; "presentedAt": (Timestamp | null); "selectedAt": (Timestamp | null); "expiresAt": Timestamp; "routeId": (Id | null); "completedVisitId": (Id | null); "feedback": string };
export type Theme = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "name": string; "description": string; "recordIds": Array<Id> };
export type ThemeCreate = { "id": Id; "name": string; "description": string; "recordIds": Array<Id> };
export type ThemePatch = { "name"?: string; "description"?: string; "recordIds"?: Array<Id> };
export type Friendship = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "requesterId": Id; "recipientId": Id; "status": "pending" | "accepted" };
export type FriendshipCreate = { "id": Id; "recipientId": Id };
export type AnalysisAxis = { "key": "detour" | "newPlace" | "rest" | "alone" | "longStay" | "farTrip"; "numerator": number; "denominator": number; "value": (number | null); "unknownDays": number };
export type AnalysisResult = { "axes": Array<AnalysisAxis>; "unknown": Array<string> };
export type ComparisonResult = { "common": Array<string>; "differences": Array<string>; "unknown": Array<string> };
export type Insight = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "kind": "analysis" | "comparison"; "inputKey": string; "sourceRefs": Array<SourceRef>; "rangeStart": (Timestamp | null); "rangeEnd": (Timestamp | null); "timeZone": TimeZone; "generatorVersion": string; "model": (string | null); "summary": string; "result": (AnalysisResult | ComparisonResult); "review": ("agree" | "disagree" | "unsure" | "edit" | null); "reviewNote": (string | null); "reviewedAt": (Timestamp | null) };
export type InsightPatch = { "review"?: ("agree" | "disagree" | "unsure" | "edit" | null); "reviewNote"?: (string | null) };
export type RecordView = { "id": Id; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp; "personId": Id; "kind": "experience" | "diary" | "memo"; "visitId": (Id | null); "placeId": (Id | null); "occurredAt": (Timestamp | null); "endedAt": (Timestamp | null); "timePrecision": "exact" | "approximate" | "unknown"; "body": string; "purposes": Array<string>; "activities": Array<Activity>; "impression": string; "periodAnswers": PeriodAnswers; "bookmarked": boolean; "useForSuggestions": boolean; "topicKey": (string | null); "visibility": "private" | "selected" | "public"; "sharedWith": Array<Id>; "effectivePlaceId": (Id | null); "effectiveStartedAt": (Timestamp | null); "effectiveEndedAt": (Timestamp | null); "effectiveTimePrecision": "exact" | "approximate" | "unknown" };
export type Error = { "code": "INVALID_REQUEST" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "STATE_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "INPUT_CHANGED" | "RESULT_EXPIRED" | "VERSION_CONFLICT" | "VERSION_REQUIRED" | "VALIDATION_FAILED" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "RATE_LIMITED" | "UPSTREAM_FAILED" | "UNAVAILABLE" | "TIMEOUT" | "INTERNAL_ERROR" | "NOT_READY" | "INVALID_INPUT" | "PERSON_REQUIRED" | "REQUEST_CONFLICT" | "BUSY" | "SOURCE_CHANGED" | "INPUT_TOO_LARGE" | "OUTPUT_INVALID" | "ROUTE_NOT_FOUND" | "MODE_UNSUPPORTED" | "PROVIDER_UNAVAILABLE" | "RANGE_NOT_SATISFIABLE"; "message": string; "requestId": Id; "details"?: { "currentVersion"?: Version; "fields"?: Array<{ "path": string; "reason": string }>; "retryAfterSec"?: number; "retryable"?: boolean } };
export type ErrorEnvelope = { "error": Error };
export type MediaPage = { "items": Array<Media>; "nextCursor": (string | null) };
export type RecordDetail = { "record": RecordView; "media": ({ "status": "ready"; "data": MediaPage } | { "status": "failed"; "error": Error }) };
export type PlacePage = { "items": Array<Place>; "nextCursor": (string | null) };
export type VisitPage = { "items": Array<Visit>; "nextCursor": (string | null) };
export type RecordViewPage = { "items": Array<RecordView>; "nextCursor": (string | null) };
export type PlaceDetail = { "place": CommonMapPlace; "colocated": Array<{ "id": string; "name": string; "address": (string | null); "coordinates": [number, number] }>; "ownRecords": { "status": "ready" | "failed"; "items": Array<CommonInfoRecordView>; "error": (CommonInfoError | null) }; "sharedRecords": { "status": "ready" | "failed"; "items": Array<CommonInfoRecordView>; "error": (CommonInfoError | null) }; "visits": { "status": "ready" | "failed"; "items": Array<CommonInfoVisitView>; "error": (CommonInfoError | null) } };
export type Candidate = { "candidateId": string; "placeId": (string | null); "name": string; "address": (string | null); "position": Position; "categories": Array<string>; "provider": string; "externalId": (string | null); "buildingKey": (string | null); "sourceUrl": (string | null); "attribution": string; "fetchedAt": (number | null); "retention": "storable" | "temporary" };
export type CandidateResult = { "resultId": Id; "expiresAt": Timestamp; "items": Array<Candidate> };
export type PlaceCreate = ({ "id": Id; "mode": "candidate"; "resultId": Id; "candidateId": Id } | { "id": Id; "mode": "manual"; "name": string; "position": Position; "address": (string | null); "buildingKey": (string | null) });
export type GrowthItem = { "place": Place; "confirmedVisitCount": number; "purposes": Array<string>; "sourceRefs": Array<SourceRef> };
export type RouteSearchResult = { "resultId": string; "waypoints": Array<{ "coordinates": [number, number]; "name": string; "placeId": (string | null) }>; "mode": "walking" | "cycling" | "driving" | "transit"; "legs": Array<{ "fromIndex": number; "toIndex": number; "geometry": CommonMapGeometry; "distanceM": number; "durationSec": number }>; "geometry": CommonMapGeometry; "distanceM": number; "durationSec": number; "provider": "mapbox-directions"; "fetchedAt": number; "expiresAt": number; "retention": "storable" | "temporary" };
export type RouteSearchInput = { "waypoints": Array<({ "kind": "stored"; "placeId": string } | { "kind": "candidate"; "resultId": string; "candidateId": string } | { "kind": "point"; "coordinates": [number, number]; "label": string })>; "mode": "walking" | "cycling" | "driving" | "transit"; "title": string };
export type SavedRouteCreate = { "id": Id; "resultId": Id; "title": string };
export type SavedRoutePatch = { "title"?: string; "resultId"?: Id; "status"?: "saved" | "navigating" | "finished"; "currentLeg"?: number; "visibility"?: "private" | "selected" | "public"; "sharedWith"?: Array<Id> };
export type SuggestionBatchInput = { "id": Id; "checkin": (SourceRef | null); "origin": Position; "conditions": SuggestionConditions; "excludedActivities": Array<string>; "excludedPlaceIds": Array<Id>; "expiresAt": Timestamp };
export type SuggestionBatch = { "id": Id; "items": Array<Suggestion> };
export type SuggestionPatch = { "status"?: "offered" | "later" | "dismissed" | "selected" | "completed" | "not_done"; "presented"?: true; "routeId"?: (Id | null); "completedVisitId"?: (Id | null); "feedback"?: string };
export type MediaUpload = { "id": Id; "file": Blob; "position": number };
export type MediaOrderInput = { "items": Array<{ "id": Id; "version": Version }> };
export type VersionedId = { "id": Id; "version": Version };
export type TrackDelete = { "segmentId": (Id | null); "from": Timestamp; "to": Timestamp; "targets": Array<VersionedId> };
export type DeletedCount = { "deletedCount": number };
export type SourceLookupInput = { "refs": Array<CommonInfoSourceRef> };
export type SourceLookup = Array<CommonInfoSourceCheck>;
export type SelfCheckinPage = { "items": Array<SelfCheckin>; "nextCursor": (string | null) };
export type DailyReflection = { "date": Date; "timeZone": TimeZone; "from": Timestamp; "to": Timestamp; "visits": ({ "status": "ready"; "data": VisitPage } | { "status": "failed"; "error": Error }); "records": ({ "status": "ready"; "data": RecordViewPage } | { "status": "failed"; "error": Error }); "checkins": ({ "status": "ready"; "data": SelfCheckinPage } | { "status": "failed"; "error": Error }) };
export type Summary = { "from": Timestamp; "to": Timestamp; "timeZone": TimeZone; "result": AnalysisResult; "sourceRefs": Array<SourceRef> };
export type MessageSend = ({ "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "extract"; "context": CommonAIextractInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "diary"; "context": CommonAIdiaryInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "consult"; "context": CommonAIconsultInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "comparison"; "context": CommonAIcompareInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "analysis"; "context": CommonAIanalysisInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "theme-name"; "context": CommonAIthemeInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "map-style"; "context": CommonAImapstyleInput; "expectedRefs": Array<CommonAISourceRef> } | { "userMessageId": Id; "assistantMessageId": Id; "body": string; "use": "discovery"; "context": CommonAIdiscoverInput; "expectedRefs": Array<CommonAISourceRef> });
export type MessageAccepted = { "userMessage": Message; "assistantMessage": Message; "statusUrl": string };
export type MessageRetry = { "attempt": number };
export type AIOutput = ({ "use": "extract"; "value": CommonAIextractResult } | { "use": "diary"; "value": CommonAIdiaryResult } | { "use": "consult"; "value": CommonAIconsultResult } | { "use": "comparison"; "value": CommonAIcompareResult } | { "use": "analysis"; "value": CommonAIanalysisResult } | { "use": "theme-name"; "value": CommonAIthemeResult } | { "use": "map-style"; "value": CommonAImapstyleResult } | { "use": "discovery"; "value": CommonAIdiscoverResult });
export type MessageResult = { "message": Message; "run": (CommonAIRun | null); "output": (AIOutput | null) };
export type RetryAccepted = { "message": Message; "statusUrl": string };
export type PluginDefinition = { "id": Id; "name": string; "description": string; "settingsSchema": { [key: string]: unknown }; "installed": (PluginSetting | null) };
export type GrowthItemPage = { "items": Array<GrowthItem>; "nextCursor": (string | null) };
export type TrackPointPage = { "items": Array<TrackPoint>; "nextCursor": (string | null) };
export type ConversationPage = { "items": Array<Conversation>; "nextCursor": (string | null) };
export type ThemePage = { "items": Array<Theme>; "nextCursor": (string | null) };
export type InsightPage = { "items": Array<Insight>; "nextCursor": (string | null) };
export type SuggestionPage = { "items": Array<Suggestion>; "nextCursor": (string | null) };
export type SavedRoutePage = { "items": Array<SavedRoute>; "nextCursor": (string | null) };
export type TransitPassPage = { "items": Array<TransitPass>; "nextCursor": (string | null) };
export type PersonPage = { "items": Array<Person>; "nextCursor": (string | null) };
export type FriendshipPage = { "items": Array<Friendship>; "nextCursor": (string | null) };
export type PluginSettingPage = { "items": Array<PluginSetting>; "nextCursor": (string | null) };
export type FeatureRequestPage = { "items": Array<FeatureRequest>; "nextCursor": (string | null) };
export type CommonAISourceRef = { "type": "record" | "visit" | "place" | "checkin" | "route"; "id": string; "version": number };
export type CommonAIError = { "code": string; "message": string; "retryable": boolean };
export type CommonAIRun = ({ "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "extract"; "result": ({ "purpose": (string | null); "reason": (string | null); "context": { "weather": ("clear" | "rain" | "snow" | "other" | null); "companion": ("alone" | "friend" | "family" | "colleague" | "other" | null); "timeBudgetMinutes": (number | null); "timeBand": ("morning" | "day" | "evening" | "night" | null); "notes": (string | null) }; "evidenceIds": Array<string>; "question": ({ "topic": "purpose" | "reason" | "context" | "alternative"; "text": string } | null) } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "diary"; "result": ({ "text": string; "evidenceIds": Array<string> } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "consult"; "result": ({ "summary": string; "candidates": Array<{ "placeId": string; "reason": string; "evidenceIds": Array<string>; "unknowns": Array<string> }>; "unknowns": Array<string> } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "compare"; "result": ({ "mappings": Array<{ "fromRecordId": string; "toRecordId": string; "relation": "same-place-same-purpose" | "same-place-different-purpose" | "different-place-same-role" | "practical-tip" | "similar-but-different-reason"; "explanation": string; "evidenceIds": Array<string>; "rejected": false }> } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "analysis"; "result": ({ "summary": string; "evidenceIds": Array<string>; "unknowns": Array<string> } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "theme"; "result": ({ "name": string; "description": string; "evidenceIds": Array<string> } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "mapstyle"; "result": ({ "proposal": { "theme": "default" | "faded" | "monochrome"; "lightPreset": "dawn" | "day" | "dusk" | "night"; "showPedestrianRoads": boolean; "showAdminBoundaries": boolean; "showIndoor": boolean; "colors": ({ "water": string; "greenspace": string; "roads": string; "buildings": string } | null) }; "explanation": string } | null) } | { "id": string; "conversationId": string; "userMessageId": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "version": number; "model": string; "promptVersion": string; "error": (CommonAIError | null); "sourceRefs": Array<CommonAISourceRef>; "insightId": (string | null); "createdAt": number; "updatedAt": number; "task": "discover"; "result": ({ "anchor": { "kind": "place" | "building" | "photo"; "targetId": string; "features": Array<string> }; "bridge": string; "knowledge": string; "observationPrompt": string; "conceptIds": Array<string>; "sources": Array<{ "url": (string | null); "title": string; "claimScope": "general" | "place-specific"; "sourceId": (string | null) }> } | null) });
export type CommonAIMessage = { "id": string; "conversationId": string; "position": number; "role": "user" | "assistant"; "body": string; "status": "pending" | "running" | "complete" | "failed" | "cancelled"; "attempt": number; "model": (string | null); "insightId": (string | null); "sourceRefs": Array<CommonAISourceRef>; "version": number; "createdAt": number; "updatedAt": number };
export type CommonAIMessagePage = { "items": Array<CommonAIMessage>; "nextCursor": (string | null) };
export type CommonAIOrigin = { "coordinates": [number, number]; "label": string; "kind": "current-location" | "map-center" | "selected" | "demo" };
export type CommonAIDialogueRequest = { "text": string; "origin": CommonAIOrigin };
export type CommonAIDialogueSelect = { "resultId": string; "candidateId": string };
export type CommonAIDialogueCancel = { "requestId": string };
export type CommonAIDialogueResult = { "resultId": string; "text": string; "places": Array<CommonMapPlaceCandidate>; "routes": Array<CommonMapRoutePreview>; "origin": CommonAIOrigin; "expiresAt": number };
export type CommonAIextractInput = { "recordId": string; "answers": Array<{ "question": string; "text": string }> };
export type CommonAIextractResult = { "purpose": (string | null); "reason": (string | null); "context": { "weather": ("clear" | "rain" | "snow" | "other" | null); "companion": ("alone" | "friend" | "family" | "colleague" | "other" | null); "timeBudgetMinutes": (number | null); "timeBand": ("morning" | "day" | "evening" | "night" | null); "notes": (string | null) }; "evidenceIds": Array<string>; "question": ({ "topic": "purpose" | "reason" | "context" | "alternative"; "text": string } | null) };
export type CommonAIdiaryInput = { "date": string; "timezone": string; "recordIds": Array<string> };
export type CommonAIdiaryResult = { "text": string; "evidenceIds": Array<string> };
export type CommonAIconsultInput = { "placeIds": Array<string>; "recordIds": Array<string>; "conditions": string };
export type CommonAIconsultResult = { "summary": string; "candidates": Array<{ "placeId": string; "reason": string; "evidenceIds": Array<string>; "unknowns": Array<string> }>; "unknowns": Array<string> };
export type CommonAIcompareInput = { "fromRecordIds": Array<string>; "toRecordIds": Array<string> };
export type CommonAIcompareResult = { "mappings": Array<{ "fromRecordId": string; "toRecordId": string; "relation": "same-place-same-purpose" | "same-place-different-purpose" | "different-place-same-role" | "practical-tip" | "similar-but-different-reason"; "explanation": string; "evidenceIds": Array<string>; "rejected": false }> };
export type CommonAIanalysisInput = { "insightId": string };
export type CommonAIanalysisResult = { "summary": string; "evidenceIds": Array<string>; "unknowns": Array<string> };
export type CommonAIthemeInput = { "recordIds": Array<string>; "currentName": string };
export type CommonAIthemeResult = { "name": string; "description": string; "evidenceIds": Array<string> };
export type CommonAImapstyleInput = { "current": { "theme": "default" | "faded" | "monochrome"; "lightPreset": "dawn" | "day" | "dusk" | "night"; "showPedestrianRoads": boolean; "showAdminBoundaries": boolean; "showIndoor": boolean; "colors": ({ "water": string; "greenspace": string; "roads": string; "buildings": string } | null) } };
export type CommonAImapstyleResult = { "proposal": { "theme": "default" | "faded" | "monochrome"; "lightPreset": "dawn" | "day" | "dusk" | "night"; "showPedestrianRoads": boolean; "showAdminBoundaries": boolean; "showIndoor": boolean; "colors": ({ "water": string; "greenspace": string; "roads": string; "buildings": string } | null) }; "explanation": string };
export type CommonAIdiscoverInput = { "anchor": { "kind": "place" | "building" | "photo"; "targetId": string; "features": Array<string> }; "factKeys": Array<string> };
export type CommonAIdiscoverResult = { "anchor": { "kind": "place" | "building" | "photo"; "targetId": string; "features": Array<string> }; "bridge": string; "knowledge": string; "observationPrompt": string; "conceptIds": Array<string>; "sources": Array<{ "url": (string | null); "title": string; "claimScope": "general" | "place-specific"; "sourceId": (string | null) }> };
export type CommonMapGeometry = { "type": "LineString"; "coordinates": Array<[number, number]> };
export type CommonMapPlace = { "id": string; "name": string; "address": (string | null); "coordinates": [number, number]; "categories": Array<string>; "provider": string; "externalId": (string | null); "buildingKey": (string | null); "sourceUrl": (string | null); "attribution": string; "fetchedAt": (number | null); "version": number; "createdAt": number; "updatedAt": number };
export type CommonMapPlaceCandidate = { "candidateId": string; "placeId": (string | null); "name": string; "address": (string | null); "coordinates": [number, number]; "categories": Array<string>; "provider": string; "externalId": (string | null); "buildingKey": (string | null); "sourceUrl": (string | null); "attribution": string; "fetchedAt": (number | null); "retention": "storable" | "temporary" };
export type CommonMapRoutePreview = { "previewId": string; "waypoints": Array<{ "coordinates": [number, number]; "name": string; "placeId": (string | null) }>; "mode": "walking" | "cycling" | "driving" | "transit"; "legs": Array<{ "fromIndex": number; "toIndex": number; "geometry": CommonMapGeometry; "distanceM": number; "durationSec": number }>; "geometry": CommonMapGeometry; "distanceM": number; "durationSec": number; "provider": "mapbox-directions"; "fetchedAt": number; "expiresAt": number; "retention": "storable" | "temporary" };
export type CommonInfoSourceRef = { "type": "record" | "visit" | "place" | "checkin" | "route"; "id": string; "version": number };
export type CommonInfoError = { "code": string; "message": string; "retryable": boolean };
export type CommonInfoMediaView = { "id": string; "kind": "photo" | "video" | "audio"; "mimeType": string; "byteSize": number; "position": number; "status": "pending" | "ready" | "failed"; "contentUrl": (string | null) };
export type CommonInfoRecordView = { "id": string; "person": { "id": string; "displayName": string; "iconPath": (string | null) }; "kind": "experience" | "diary" | "memo"; "body": string; "place": ({ "id": string; "name": string; "address": (string | null); "coordinates": [number, number] } | null); "effectiveAt": (number | null); "endedAt": (number | null); "timePrecision": "exact" | "approximate" | "unknown"; "visitStatus": ("candidate" | "confirmed" | "rejected" | null); "purposes": Array<string>; "impression": string; "topicKey": (string | null); "visibility": "private" | "selected" | "public"; "version": number; "sourceRefs": Array<CommonInfoSourceRef>; "media": Array<CommonInfoMediaView> };
export type CommonInfoRecordPage = { "items": Array<CommonInfoRecordView>; "nextCursor": (string | null); "totalCount": number };
export type CommonInfoRecordMap = { "items": Array<{ "recordId": string; "personId": string; "placeId": string; "coordinates": [number, number]; "mediaId": (string | null) }>; "totalCount": number };
export type CommonInfoSourceCheck = { "ref": CommonInfoSourceRef; "state": "current" | "changed" | "unavailable"; "currentVersion": (number | null) };
export type CommonInfoVisitView = { "id": string; "placeId": string; "startedAt": (number | null); "endedAt": (number | null); "timePrecision": "exact" | "approximate" | "unknown"; "origin": "manual" | "gps"; "status": "candidate" | "confirmed" | "rejected"; "version": number; "createdAt": number; "updatedAt": number };
export type DiscoveryCard = { "id": Id; "personId": Id; "anchor": { "kind": "place" | "building" | "photo"; "targetId": string; "features": Array<string> }; "bridge": string; "knowledge": string; "observationPrompt": string; "conceptIds": Array<string>; "sources": Array<{ "url": (string | null); "title": string; "claimScope": "general" | "place-specific"; "sourceId": (string | null) }>; "sourceRefs": Array<CommonAISourceRef>; "version": Version; "createdAt": Timestamp; "updatedAt": Timestamp };
export type DiscoveryReaction = { "id": Id; "personId": Id; "cardId": Id; "reaction": "known" | "interested" | "saved" | "blocked" | "dismissed"; "createdAt": Timestamp };
export type DiscoveryCardPage = { "items": Array<DiscoveryCard>; "nextCursor": (string | null) };
export type DiscoveryReactionPage = { "items": Array<DiscoveryReaction>; "nextCursor": (string | null) };
export type LocalProfile = { "profileKey": string; "name": string };
export type SessionInput = { "profileKey": string };
export type LocalSession = { "person": Person; "dataMode": DataMode; "version": number; "expiresAt": number };
export type DataMode = "live" | "demo";

export interface OperationMap {
  "getPlaces": { input: { query?: { "q"?: string; "bbox"?: string; "buildingKey"?: string; "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: PlacePage };
  "postPlaces": { input: { body: PlaceCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Place } };
  "getPlaceCandidates": { input: { query?: { "q"?: string; "longitude"?: number; "latitude"?: number; "category"?: "coffee" | "restaurant" | "bakery" | "park"; "limit"?: number }; signal?: AbortSignal }; output: { "data": CandidateResult } };
  "getPlacesPlaceId": { input: { path: { "placeId": Id }; signal?: AbortSignal }; output: { "data": PlaceDetail } };
  "patchPlacesPlaceId": { input: { path: { "placeId": Id }; body: PlacePatch; version: number; signal?: AbortSignal }; output: { "data": Place } };
  "getMapGrowth": { input: { query?: { "bbox"?: string; "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: GrowthItemPage };
  "getVisits": { input: { query?: { "placeId"?: Id; "from"?: Timestamp; "to"?: Timestamp; "cursor"?: string; "limit"?: number; "status"?: "candidate" | "confirmed" | "rejected" }; signal?: AbortSignal }; output: VisitPage };
  "postVisits": { input: { body: VisitCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Visit } };
  "getVisitsVisitId": { input: { path: { "visitId": Id }; signal?: AbortSignal }; output: { "data": Visit } };
  "patchVisitsVisitId": { input: { path: { "visitId": Id }; body: VisitPatch; version: number; signal?: AbortSignal }; output: { "data": Visit } };
  "deleteVisitsVisitId": { input: { path: { "visitId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getRecords": { input: { query?: { "placeId"?: Id; "themeId"?: Id; "from"?: Timestamp; "to"?: Timestamp; "cursor"?: string; "limit"?: number; "kind"?: "experience" | "diary" | "memo"; "timeZone"?: TimeZone; "includeUndated"?: boolean }; signal?: AbortSignal }; output: RecordViewPage };
  "postRecords": { input: { body: RecordCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": RecordView } };
  "getRecordsRecordId": { input: { path: { "recordId": Id }; signal?: AbortSignal }; output: { "data": RecordDetail } };
  "patchRecordsRecordId": { input: { path: { "recordId": Id }; body: RecordPatch; version: number; signal?: AbortSignal }; output: { "data": RecordView } };
  "deleteRecordsRecordId": { input: { path: { "recordId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getRecordsRecordIdMedia": { input: { path: { "recordId": Id }; query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: MediaPage };
  "postRecordsRecordIdMedia": { input: { path: { "recordId": Id }; body: FormData; version: number; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Media } };
  "postRecordsRecordIdMediaReorder": { input: { path: { "recordId": Id }; body: MediaOrderInput; version: number; idempotencyKey: string; signal?: AbortSignal }; output: MediaPage };
  "getMediaMediaId": { input: { path: { "mediaId": Id }; signal?: AbortSignal }; output: { "data": Media } };
  "deleteMediaMediaId": { input: { path: { "mediaId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getMediaMediaIdContent": { input: { path: { "mediaId": Id }; signal?: AbortSignal }; output: Blob };
  "getTrackPoints": { input: { query?: { "segmentId"?: Id; "from"?: Timestamp; "to"?: Timestamp; "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: TrackPointPage };
  "postTrackPoints": { input: { body: { "items": Array<TrackPointCreate> }; idempotencyKey: string; signal?: AbortSignal }; output: { "data": { "items": Array<TrackPoint> } } };
  "getTrackPointsPointId": { input: { path: { "pointId": Id }; signal?: AbortSignal }; output: { "data": TrackPoint } };
  "postTrackPointsDeleteRange": { input: { body: TrackDelete; idempotencyKey: string; signal?: AbortSignal }; output: { "data": DeletedCount } };
  "getConversations": { input: { query?: { "cursor"?: string; "limit"?: number; "purpose"?: "consult" | "reflection" | "analysis" | "comparison" }; signal?: AbortSignal }; output: ConversationPage };
  "postConversations": { input: { body: ConversationCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Conversation } };
  "getConversationsConversationId": { input: { path: { "conversationId": Id }; signal?: AbortSignal }; output: { "data": Conversation } };
  "patchConversationsConversationId": { input: { path: { "conversationId": Id }; body: ConversationPatch; version: number; signal?: AbortSignal }; output: { "data": Conversation } };
  "deleteConversationsConversationId": { input: { path: { "conversationId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getConversationsConversationIdMessages": { input: { path: { "conversationId": Id }; query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: CommonAIMessagePage };
  "postConversationsConversationIdMessages": { input: { path: { "conversationId": Id }; body: MessageSend; idempotencyKey: string; signal?: AbortSignal }; output: { "data": MessageAccepted } };
  "getMessagesMessageId": { input: { path: { "messageId": Id }; signal?: AbortSignal }; output: { "data": MessageResult } };
  "postMessagesMessageIdCancel": { input: { path: { "messageId": Id }; body: MessageRetry; version: number; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Message } };
  "postMessagesMessageIdRetry": { input: { path: { "messageId": Id }; body: MessageRetry; version: number; idempotencyKey: string; signal?: AbortSignal }; output: { "data": RetryAccepted } };
  "getReflectionDaysDate": { input: { path: { "date": Date }; query: { "timeZone": TimeZone }; signal?: AbortSignal }; output: { "data": DailyReflection } };
  "getSelfCheckins": { input: { query?: { "date"?: Date; "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: SelfCheckinPage };
  "postSelfCheckins": { input: { body: SelfCheckinCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": SelfCheckin } };
  "getSelfCheckinsCheckinId": { input: { path: { "checkinId": Id }; signal?: AbortSignal }; output: { "data": SelfCheckin } };
  "patchSelfCheckinsCheckinId": { input: { path: { "checkinId": Id }; body: SelfCheckinPatch; version: number; signal?: AbortSignal }; output: { "data": SelfCheckin } };
  "deleteSelfCheckinsCheckinId": { input: { path: { "checkinId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getThemes": { input: { query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: ThemePage };
  "postThemes": { input: { body: ThemeCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Theme } };
  "getThemesThemeId": { input: { path: { "themeId": Id }; signal?: AbortSignal }; output: { "data": Theme } };
  "patchThemesThemeId": { input: { path: { "themeId": Id }; body: ThemePatch; version: number; signal?: AbortSignal }; output: { "data": Theme } };
  "deleteThemesThemeId": { input: { path: { "themeId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getReflectionSummary": { input: { query: { "from": Timestamp; "to": Timestamp; "timeZone": TimeZone }; signal?: AbortSignal }; output: { "data": Summary } };
  "getInsights": { input: { query?: { "from"?: Timestamp; "to"?: Timestamp; "cursor"?: string; "limit"?: number; "kind"?: "analysis" | "comparison" }; signal?: AbortSignal }; output: InsightPage };
  "postInsights": { input: { body: { "id": Id; "from": Timestamp; "to": Timestamp; "timeZone": TimeZone }; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Insight } };
  "getInsightsInsightId": { input: { path: { "insightId": Id }; signal?: AbortSignal }; output: { "data": Insight } };
  "patchInsightsInsightId": { input: { path: { "insightId": Id }; body: InsightPatch; version: number; signal?: AbortSignal }; output: { "data": Insight } };
  "deleteInsightsInsightId": { input: { path: { "insightId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "postSourceChecks": { input: { body: SourceLookupInput; idempotencyKey: string; signal?: AbortSignal }; output: { "data": SourceLookup } };
  "postSuggestionBatches": { input: { body: SuggestionBatchInput; idempotencyKey: string; signal?: AbortSignal }; output: { "data": SuggestionBatch } };
  "getSuggestions": { input: { query?: { "batchId"?: Id; "cursor"?: string; "limit"?: number; "status"?: "offered" | "later" | "dismissed" | "selected" | "completed" | "not_done" }; signal?: AbortSignal }; output: SuggestionPage };
  "getSuggestionsSuggestionId": { input: { path: { "suggestionId": Id }; signal?: AbortSignal }; output: { "data": Suggestion } };
  "patchSuggestionsSuggestionId": { input: { path: { "suggestionId": Id }; body: SuggestionPatch; version: number; signal?: AbortSignal }; output: { "data": Suggestion } };
  "postRouteSearches": { input: { body: RouteSearchInput; idempotencyKey: string; signal?: AbortSignal }; output: { "data": RouteSearchResult } };
  "getSavedRoutes": { input: { query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: SavedRoutePage };
  "postSavedRoutes": { input: { body: SavedRouteCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": SavedRoute } };
  "getSavedRoutesRouteId": { input: { path: { "routeId": Id }; signal?: AbortSignal }; output: { "data": SavedRoute } };
  "patchSavedRoutesRouteId": { input: { path: { "routeId": Id }; body: SavedRoutePatch; version: number; signal?: AbortSignal }; output: { "data": SavedRoute } };
  "deleteSavedRoutesRouteId": { input: { path: { "routeId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getTransitPasses": { input: { query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: TransitPassPage };
  "postTransitPasses": { input: { body: TransitPassCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": TransitPass } };
  "getTransitPassesPassId": { input: { path: { "passId": Id }; signal?: AbortSignal }; output: { "data": TransitPass } };
  "patchTransitPassesPassId": { input: { path: { "passId": Id }; body: TransitPassPatch; version: number; signal?: AbortSignal }; output: { "data": TransitPass } };
  "deleteTransitPassesPassId": { input: { path: { "passId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getMe": { input: { signal?: AbortSignal }; output: { "data": Person } };
  "patchMe": { input: { body: PersonPatch; version: number; signal?: AbortSignal }; output: { "data": Person } };
  "getPeople": { input: { query?: { "q"?: string; "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: PersonPage };
  "getPeoplePersonId": { input: { path: { "personId": Id }; signal?: AbortSignal }; output: { "data": Person } };
  "getFriendships": { input: { query?: { "cursor"?: string; "limit"?: number; "status"?: "pending" | "accepted" }; signal?: AbortSignal }; output: FriendshipPage };
  "postFriendships": { input: { body: FriendshipCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": Friendship } };
  "getFriendshipsFriendshipId": { input: { path: { "friendshipId": Id }; signal?: AbortSignal }; output: { "data": Friendship } };
  "patchFriendshipsFriendshipId": { input: { path: { "friendshipId": Id }; body: { "status": "accepted" }; version: number; signal?: AbortSignal }; output: { "data": Friendship } };
  "deleteFriendshipsFriendshipId": { input: { path: { "friendshipId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getSharedRecords": { input: { query?: { "q"?: string; "placeId"?: Id; "longitude"?: number; "latitude"?: number; "radiusM"?: number; "from"?: Timestamp; "to"?: Timestamp; "timeZone"?: TimeZone; "cursor"?: string; "limit"?: number; "audience"?: "own" | "visible" | "public" | "selected" | "friends"; "personIds"?: Array<string>; "purposes"?: Array<string>; "topicKey"?: (string | null); "includeUndated"?: boolean }; signal?: AbortSignal }; output: CommonInfoRecordPage };
  "getSharedRecordsMap": { input: { query?: { "q"?: string; "placeId"?: Id; "longitude"?: number; "latitude"?: number; "radiusM"?: number; "from"?: Timestamp; "to"?: Timestamp; "timeZone"?: TimeZone; "audience"?: "own" | "visible" | "public" | "selected" | "friends"; "personIds"?: Array<string>; "purposes"?: Array<string>; "topicKey"?: (string | null); "includeUndated"?: boolean }; signal?: AbortSignal }; output: { "data": CommonInfoRecordMap } };
  "getPlacesPlaceIdVoices": { input: { path: { "placeId": Id }; query: { "q"?: string; "longitude"?: number; "latitude"?: number; "radiusM"?: number; "from"?: Timestamp; "to"?: Timestamp; "timeZone"?: TimeZone; "cursor"?: string; "limit"?: number; "audience"?: "own" | "visible" | "public" | "selected" | "friends"; "personIds"?: Array<string>; "purposes"?: Array<string>; "topicKey": (string | null); "includeUndated"?: boolean }; signal?: AbortSignal }; output: CommonInfoRecordPage };
  "getSharedRoutes": { input: { query?: { "personId"?: Id; "visibility"?: "private" | "selected" | "public"; "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: SavedRoutePage };
  "getPlugins": { input: { signal?: AbortSignal }; output: { "items": Array<PluginDefinition> } };
  "getPluginSettings": { input: { query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: PluginSettingPage };
  "postPluginSettings": { input: { body: PluginSettingCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": PluginSetting } };
  "getPluginSettingsPluginId": { input: { path: { "pluginId": Id }; signal?: AbortSignal }; output: { "data": PluginSetting } };
  "patchPluginSettingsPluginId": { input: { path: { "pluginId": Id }; body: PluginSettingPatch; version: number; signal?: AbortSignal }; output: { "data": PluginSetting } };
  "deletePluginSettingsPluginId": { input: { path: { "pluginId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "getFeatureRequests": { input: { query?: { "personId"?: Id; "cursor"?: string; "limit"?: number; "visibility"?: "private" | "public" }; signal?: AbortSignal }; output: FeatureRequestPage };
  "postFeatureRequests": { input: { body: FeatureRequestCreate; idempotencyKey: string; signal?: AbortSignal }; output: { "data": FeatureRequest } };
  "getFeatureRequestsRequestId": { input: { path: { "requestId": Id }; signal?: AbortSignal }; output: { "data": FeatureRequest } };
  "patchFeatureRequestsRequestId": { input: { path: { "requestId": Id }; body: FeatureRequestPatch; version: number; signal?: AbortSignal }; output: { "data": FeatureRequest } };
  "deleteFeatureRequestsRequestId": { input: { path: { "requestId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "postMapDialogues": { input: { body: CommonAIDialogueRequest; idempotencyKey: string; signal?: AbortSignal }; output: { "data": CommonAIDialogueResult } };
  "postMapDialoguesSelect": { input: { body: CommonAIDialogueSelect; idempotencyKey: string; signal?: AbortSignal }; output: { "data": CommonAIDialogueResult } };
  "postMapDialoguesCancel": { input: { body: CommonAIDialogueCancel; idempotencyKey: string; signal?: AbortSignal }; output: undefined };
  "getMapDialoguesResultsResultId": { input: { path: { "resultId": Id }; signal?: AbortSignal }; output: { "data": CommonAIDialogueResult } };
  "postDiscoveryCards": { input: { body: { "id": Id; "assistantMessageId": Id; "expectedAttempt": number }; idempotencyKey: string; signal?: AbortSignal }; output: { "data": DiscoveryCard } };
  "getDiscoveryCards": { input: { query?: { "cursor"?: string; "limit"?: number; "savedOnly"?: boolean }; signal?: AbortSignal }; output: DiscoveryCardPage };
  "getDiscoveryCardsCardId": { input: { path: { "cardId": Id }; signal?: AbortSignal }; output: { "data": DiscoveryCard } };
  "deleteDiscoveryCardsCardId": { input: { path: { "cardId": Id }; version: number; signal?: AbortSignal }; output: undefined };
  "postDiscoveryCardsCardIdReactions": { input: { path: { "cardId": Id }; body: { "id": Id; "reaction": "known" | "interested" | "saved" | "blocked" | "dismissed" }; idempotencyKey: string; signal?: AbortSignal }; output: { "data": DiscoveryReaction } };
  "getDiscoveryCardsCardIdReactions": { input: { path: { "cardId": Id }; query?: { "cursor"?: string; "limit"?: number }; signal?: AbortSignal }; output: DiscoveryReactionPage };
  "getDiscoveryCardsCardIdReactionsReactionId": { input: { path: { "cardId": Id; "reactionId": Id }; signal?: AbortSignal }; output: { "data": DiscoveryReaction } };
  "getSessionProfiles": { input: { signal?: AbortSignal }; output: { "items": Array<LocalProfile> } };
  "postSession": { input: { body: SessionInput; idempotencyKey: string; signal?: AbortSignal }; output: { "data": LocalSession } };
  "getSession": { input: { signal?: AbortSignal }; output: { "data": LocalSession } };
  "deleteSession": { input: { version: number; signal?: AbortSignal }; output: undefined };
}
export type OperationId = keyof OperationMap;
export type OperationInput<T extends OperationId> = OperationMap[T]["input"];
export type OperationOutput<T extends OperationId> = OperationMap[T]["output"];
