import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { existsSync, readFileSync } from 'node:fs';
const migration = new URL('../../db/migrations/themes/001-presentation.sql', import.meta.url);
test('source deletion invalidates theme and preserves independent memo body', () => {
  assert.ok(existsSync(migration), 'THEMES presentation migration is required');
  const db = new DatabaseSync(':memory:');
  db.exec(`PRAGMA foreign_keys=ON;
    CREATE TABLE people(id TEXT PRIMARY KEY);
    CREATE TABLE records(id TEXT PRIMARY KEY,person_id TEXT,kind TEXT,body TEXT,version INTEGER,updated_at INTEGER);
    CREATE TABLE media(id TEXT PRIMARY KEY,record_id TEXT REFERENCES records(id) ON DELETE CASCADE);
    CREATE TABLE themes(id TEXT PRIMARY KEY,person_id TEXT,name TEXT,description TEXT,record_ids_json TEXT,version INTEGER,created_at INTEGER,updated_at INTEGER);
    CREATE TABLE suggestions(id TEXT PRIMARY KEY);
    INSERT INTO people VALUES ('p');
    INSERT INTO records VALUES ('source','p','experience','source',1,1),('memo','p','memo','keep me',1,1);
    INSERT INTO media VALUES ('photo','source');
    INSERT INTO themes VALUES ('t','p','same','','["source"]',1,1,1);`);
  db.exec(readFileSync(migration,'utf8'));
  db.prepare('UPDATE themes SET cover_media_id=? WHERE id=?').run('photo','t');
  db.exec(`INSERT INTO memo_presentations(record_id,name) VALUES ('memo','memo name');
    INSERT INTO memo_origins(record_id,position,origin_type,origin_id,origin_version) VALUES ('memo',0,'record','source',1);
    INSERT INTO memo_keywords(record_id,position,keyword) VALUES ('memo',0,'rest');
    DELETE FROM records WHERE id='source';`);
  const theme = db.prepare('SELECT * FROM themes').get();
  assert.deepEqual(JSON.parse(theme.record_ids_json), []);
  assert.equal(theme.cover_media_id,null);
  assert.ok(theme.version>1);
  assert.equal(db.prepare("SELECT body FROM records WHERE id='memo'").get().body,'keep me');
  assert.equal(db.prepare('SELECT count(*) n FROM memo_origins').get().n,0);
  assert.equal(db.prepare('SELECT keyword FROM memo_keywords').get().keyword,'rest');
  db.exec("DELETE FROM records WHERE id='memo'");
  assert.equal(db.prepare('SELECT count(*) n FROM memo_presentations').get().n,0);
  db.close();
});
