// @vitest-environment jsdom
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { expect, it, vi } from 'vitest';
import { DisasterPanel, regions } from './DisasterPanel';
import type { DisasterLayer } from '../types';
Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });

it('keeps a failed layer inspectable and supports region changes and stopping an installed overlay', async () => {
  const onSettings = vi.fn(), onEnabled = vi.fn(), onRefresh = vi.fn();
  const layer: DisasterLayer = {layerId:'rainfall',kind:'observation',label:'降水',status:'providerError',sourceUrl:'https://www.jma.go.jp/bosai/nowc/',attribution:'気象庁',unit:'mm/h',legend:{url:'https://www.jma.go.jp/bosai/nowc/',description:'降水強度の凡例'},meaning:'解析時点の降水。現在の浸水深ではありません。',fetchedAt:1789437600000,sourceUpdatedAt:null,sourceUpdatedAtMeaning:'不明',validAt:null,issuedAt:null,bounds:[139.84,35.68,139.92,35.76],coverage:{envelope:[122,20,154,46],description:'日本'},tiles:[],noDataMask:null,unknowns:['提供元との通信に失敗しました']};
  const host = document.createElement('div'); document.body.append(host); const root = createRoot(host);
  await act(async () => root.render(<DisasterPanel settings={{region:regions[0]!,layerIds:['rainfall']}} layers={[layer]} busy={false} error="更新できませんでした" enabled installed demo={false} onSettings={onSettings} onRefresh={onRefresh} onEnabled={onEnabled} onInstall={vi.fn()} onLayer={vi.fn()} onFocus={vi.fn()} tab="layers" setTab={vi.fn()}/>));
  expect(host.querySelector('[role=alert]')?.textContent).toContain('更新できません');
  await act(async () => host.querySelector<HTMLButtonElement>('[aria-label="降水の状況の詳細"]')!.click());
  expect(host.textContent).toContain('提供元との通信に失敗しました');
  expect(host.textContent).toContain('未確認 · 不明');
  expect(host.querySelector<HTMLInputElement>('input:checked')?.disabled).toBe(true);
  const select = host.querySelector('select')!;
  await act(async () => {select.value='名古屋・本山';select.dispatchEvent(new Event('change',{bubbles:true}));});
  expect(onSettings).toHaveBeenCalledWith({region:regions[1],layerIds:['rainfall']});
  await act(async () => [...host.querySelectorAll('button')].find(button => button.textContent === '防災レイヤーを停止')!.click());
  expect(onEnabled).toHaveBeenCalledWith(false);
  await act(async () => [...host.querySelectorAll('button')].find(button => button.textContent === '再試行')!.click());
  expect(onRefresh).toHaveBeenCalledOnce();
  const lastAttempt = { attemptedAt: 1789441200000, status: 'failed' as const, settings: {region: regions[1]!, layerIds: ['rainfall' as const]}, layers: [layer] };
  const savedLayer = { ...layer, status: 'available' as const, unknowns: [] };
  await act(async () => root.render(<DisasterPanel settings={{region:regions[0]!,layerIds:['rainfall']}} layers={[savedLayer]} lastAttempt={lastAttempt} busy={false} error={null} enabled installed demo={false} onSettings={onSettings} onRefresh={onRefresh} onEnabled={onEnabled} onInstall={vi.fn()} onLayer={vi.fn()} onFocus={vi.fn()} tab="sources" setTab={vi.fn()}/>));
  const attempt = host.querySelector('[aria-label="直近の取得結果"]')!;
  expect(attempt.textContent).toContain('名古屋・本山');
  expect(attempt.textContent).toContain('直近の更新に失敗');
  expect(attempt.querySelector('summary')?.textContent).toContain('提供元から取得できません');
  expect(attempt.textContent).toContain('提供元との通信に失敗しました');
  expect(host.querySelector('.disaster-layer-card')?.textContent).toContain('取得済み');
  await act(async () => root.render(<DisasterPanel settings={lastAttempt.settings} layers={[]} lastAttempt={{...lastAttempt,status:'partial'}} busy={false} error={null} enabled installed demo={false} onSettings={onSettings} onRefresh={onRefresh} onEnabled={onEnabled} onInstall={vi.fn()} onLayer={vi.fn()} onFocus={vi.fn()} tab="sources" setTab={vi.fn()}/>));
  expect(host.textContent).toContain('一部の情報を取得できませんでした');
  expect(host.textContent).toContain('取得した情報がありません');
  const datedLayer = { ...savedLayer, issuedAt: 1789440900000, validAt: 1789441200000 };
  const savedResult = { settings: {region: regions[0]!, layerIds: ['rainfall' as const]}, fetchedAt: 1789441500000 };
  const renderSaved = (selectedRegion: typeof regions[number], issuedAt: number | null) => <DisasterPanel settings={{region:selectedRegion,layerIds:['rainfall']}} layers={[{...datedLayer,issuedAt}]} savedResult={savedResult} busy={false} error={null} enabled installed demo={false} onSettings={onSettings} onRefresh={onRefresh} onEnabled={onEnabled} onInstall={vi.fn()} onLayer={vi.fn()} onFocus={vi.fn()} tab="sources" setTab={vi.fn()}/>;
  await act(async () => root.render(renderSaved(regions[1]!, datedLayer.issuedAt)));
  expect(host.querySelector('[aria-label="保存情報の対象地域"]')?.textContent).toContain('保存情報の地域：江戸川周辺');
  expect(host.textContent).toContain('選択中の地域とは異なる保存情報');
  const definition = (name: string) => [...host.querySelectorAll('dt')].find(item => item.textContent === name)?.nextElementSibling?.textContent;
  expect(definition('解析基準時刻')).toBe(new Date(datedLayer.issuedAt).toLocaleString('ja-JP'));
  expect(definition('解析対象時刻')).toBe(new Date(datedLayer.validAt).toLocaleString('ja-JP'));
  expect(definition('取得時刻')).toBe(new Date(datedLayer.fetchedAt).toLocaleString('ja-JP'));
  // Map-center selections reuse the same name; changed bounds must still be distinguished.
  await act(async () => root.render(renderSaved({...regions[0]!, bounds: regions[1]!.bounds}, null)));
  expect(host.textContent).toContain('選択中の地域とは異なる保存情報');
  expect(definition('解析基準時刻')).toBe('未確認');
  await act(async () => root.render(renderSaved(regions[0]!, null)));
  expect(host.textContent).not.toContain('選択中の地域とは異なる保存情報');
  await act(async () => root.unmount()); host.remove();
});
