import type { PluginRelease } from '../../features/plugins/types.ts';
export const pilgrimageRelease:PluginRelease={
 manifest:{id:'pilgrimage',name:'聖地巡り',description:'作品と出典付きの地点を地域で探し、訪問順と道路経路を保存します。',category:'travel',author:'育てる地図',pluginVersion:'1.0.0',updatedAt:1789430400000,changeLog:'作品・出典検索、訪問順の保存、道路経路、AI順序提案',icon:'book',order:30,
 usageInfo:['作品名と地域を指定して検索します。','未確認の作品関連は未確認と表示します。','停止しても保存済みの計画・場所・経路・本人記録は残ります。'],
 sources:[{name:'飛騨市公式観光サイト',url:'https://www.hida-kankou.jp/courses/73',attribution:'飛騨市・事実の要約と原典リンク'},{name:'Wikidata',url:'https://www.wikidata.org/',attribution:'CC0・共同編集情報は未確認と表示'},{name:'道路経路',url:'https://www.mapbox.com/about/maps/',attribution:'Mapbox Directions（共通ROUTES）'}],
 settingsSchema:{type:'object',additionalProperties:false,required:['workQuery','region','mode'],properties:{workQuery:{type:'string',title:'作品名',maxLength:200},region:{type:'object',title:'対象地域',additionalProperties:false,required:['id','bounds'],properties:{id:{type:'string',minLength:1,maxLength:80,title:'地域名'},bounds:{type:'array',title:'西・南・東・北の境界',minItems:4,maxItems:4,items:{type:'number'},prefixItems:[{minimum:-180,maximum:180},{minimum:-90,maximum:90},{minimum:-180,maximum:180},{minimum:-90,maximum:90}]}}},mode:{type:'string',title:'移動方法',enum:['walking','driving']}}},
 defaultSettings:{workQuery:'',region:{id:'日本',bounds:[122,24,146,46]},mode:'walking'},trialConditions:['試用の地図と作品は模擬です。実在作品との対応確認・保存は通常検索で行います。']},
 declarations:()=>[{targetKey:'layer:pilgrimage',property:'visibility',value:true}],
 trial:()=>({dataKind:'mock',label:'模擬の聖地巡り（実在作品との関係はありません）',declarations:[{targetKey:'layer:pilgrimage',property:'visibility',value:true}],features:[{type:'Feature',id:'pilgrimage-trial',geometry:{type:'Point',coordinates:[139.7,35.7]},properties:{kind:'pilgrimage',label:'模擬地点・作品関連未確認',legendId:'trial',sourceIds:['trial'],status:'simulated',value:null,unit:null}}],legends:[{id:'trial',label:'模擬地点',color:'#9b6fbd',meaning:'表示確認用。実在作品との対応を示しません。'}],sources:[{id:'trial',title:'試用の模擬データ',url:null,attribution:'育てる地図',dataKind:'mock',fetchedAt:null,sourceUpdatedAt:null,observedAt:null,issuedAt:null,validAt:null}],generatedAt:Date.now(),warnings:['モックです。実検索・経路保存の完了を示すものではありません。']})
};
