import { CommonError } from '../../core/errors.ts';
import type { SearchInput, Selection, Coordinates, Region } from './types.ts';
export const invalid = (message: string) => new CommonError('INVALID_INPUT', message);
export const text = (v: unknown, max: number): v is string => typeof v === 'string' && v.trim().length > 0 && v.length <= max;
export function keys(v: any, allowed: string[]) { if (!v || typeof v !== 'object' || Array.isArray(v) || Object.keys(v).some(k => !allowed.includes(k))) throw invalid('入力項目が不正です。'); }
export function id(v: unknown): asserts v is string { if (!text(v, 80)) throw invalid('IDが不正です。'); }
export function coordinates(v: unknown): v is Coordinates { return Array.isArray(v) && v.length === 2 && v.every(Number.isFinite) && Math.abs(v[0]) <= 180 && Math.abs(v[1]) <= 90; }
export function region(v: any): asserts v is Region { keys(v, ['id', 'bounds']); id(v.id); if (!Array.isArray(v.bounds) || v.bounds.length !== 4 || !coordinates(v.bounds.slice(0,2)) || !coordinates(v.bounds.slice(2)) || v.bounds[0] >= v.bounds[2] || v.bounds[1] >= v.bounds[3]) throw invalid('地域の範囲が不正です。'); }
export function inRegion(p: Coordinates, r: Region) { return p[0] >= r.bounds[0] && p[0] <= r.bounds[2] && p[1] >= r.bounds[1] && p[1] <= r.bounds[3]; }
export function validateSearch(v: SearchInput) { keys(v, ['id','workQuery','workId','region']); id(v.id); if (!text(v.workQuery,200) || v.workId !== undefined && !/^Q[1-9][0-9]*$/.test(v.workId)) throw invalid('作品名・作品IDを確認してください。'); region(v.region); return v; }
export function validateSelection(v: Selection) { keys(v,['searchId','orderedRelationIds','mode','title','settingsVersion','acknowledgeUnverified','ai']); id(v.searchId); if (!Array.isArray(v.orderedRelationIds) || v.orderedRelationIds.length < 2 || v.orderedRelationIds.length > 10 || new Set(v.orderedRelationIds).size !== v.orderedRelationIds.length) throw invalid('異なる地点を2〜10件、訪問順で指定してください。'); v.orderedRelationIds.forEach(id); if (!['walking','driving'].includes(v.mode) || !text(v.title,100) || !Number.isSafeInteger(v.settingsVersion) || v.settingsVersion < 1 || typeof v.acknowledgeUnverified !== 'boolean') throw invalid('計画の設定が不正です。'); if (v.ai) {keys(v.ai,['runId','attempt']); id(v.ai.runId); if (!Number.isSafeInteger(v.ai.attempt) || v.ai.attempt < 1) throw invalid('AI試行番号が不正です。');} return v; }
export function distanceM(a: Coordinates,b: Coordinates) { const rad=Math.PI/180, dlat=(b[1]-a[1])*rad, dlng=(b[0]-a[0])*rad; return 12742000*Math.asin(Math.min(1,Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a[1]*rad)*Math.cos(b[1]*rad)*Math.sin(dlng/2)**2))); }
